# Generated by Django 5.2.7 on 2025-12-03 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultades', '0001_initial'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='sedes.sede'),
        ),
    ]
