# Generated by Django 4.2.26 on 2025-11-28 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[('VER', 'Ver'), ('EDITAR', 'Editar')], default='VER', max_length=20)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.componente')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
        ),
    ]
