# Generated by Django 4.2.26 on 2026-05-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('componentes', '0002_componenterol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[('VER', 'Ver'), ('EDITAR', 'Editar')], default='VER', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.componente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='componenteusuario',
            constraint=models.UniqueConstraint(fields=('componente', 'usuario'), name='uniq_componente_usuario'),
        ),
    ]
