"""
Seeder de relaciones Asignatura-Programa.
"""

from asignaturas.models import Asignatura, AsignaturaPrograma
from programas.models import Programa


def create_asignaturas_programa(stdout, style):
    """Crear relaciones entre asignaturas y programas con semestre y componente formativo"""
    stdout.write('  → Creando relaciones asignatura-programa...')
    stdout.write('     Este proceso puede tomar varios segundos...')
    
    # Mapeo de componentes formativos
    componentes_map = {
        'Básica': 'Básica',
        'Profesional': 'Profesional',
        'Humanística': 'Humanística',
        'Práctico': 'Práctico',
        'Optativa': 'Optativa',
        'Electiva': 'Electiva'
    }
    
    # Formato: (nombre_programa, codigo_asignatura, semestre, componente_formativo)
    relaciones_data = [
        ('Administración de Negocios Internacionales', 'CEA-EMPI', 1, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-EXVE', 1, 'Humanística'),
        ('Administración de Negocios Internacionales', 'CEA-FDAD', 1, 'Humanística'),
        ('Administración de Negocios Internacionales', 'CEA-FDEC', 1, 'Humanística'),
        ('Administración de Negocios Internacionales', 'CEA-FDMA', 1, 'Humanística'),
        ('Administración de Negocios Internacionales', 'CEA-FDNI', 1, 'Humanística'),
        ('Administración de Negocios Internacionales', 'CEA-PDCO', 1, 'Básica'),
        ('Administración de Negocios Internacionales', 'CSA-CATU', 1, 'Humanística'),
        ('Administración de Negocios Internacionales', 'CEA-CALC', 2, 'Básica'),
        ('Administración de Negocios Internacionales', 'CEA-COFI', 2, 'Básica'),
        ('Administración de Negocios Internacionales', 'CEA-DECO', 2, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-ECEM', 2, 'Básica'),
        ('Administración de Negocios Internacionales', 'CEA-EPMI', 2, 'Básica'),
        ('Administración de Negocios Internacionales', 'CEA-GPOR', 2, 'Básica'),
        ('Administración de Negocios Internacionales', 'CEA-COEN', 3, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-DILI', 3, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-DLSS', 3, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-ESDE', 3, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-MAFI', 3, 'Básica'),
        ('Administración de Negocios Internacionales', 'CEA-PREM', 3, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-SICO', 3, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-ADFI', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-COEI', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-ESIN', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-FDME', 4, 'Humanística'),
        ('Administración de Negocios Internacionales', 'CEA-GEOP', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-GTHA', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-LEAD', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-CONG', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-DCIN', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-DINO', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-FICO', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-INOP', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-LDFI', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-MOIN', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-ELE1', 6, 'Electiva'),
        ('Administración de Negocios Internacionales', 'CEA-FGPR', 6, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-FIIN', 6, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-GIMP', 6, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-GTIN', 6, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-INME', 6, 'Básica'),
        ('Administración de Negocios Internacionales', 'CEA-OEF1', 6, 'Optativa'),
        ('Administración de Negocios Internacionales', 'CEA-OPT1', 6, 'Optativa'),
        ('Administración de Negocios Internacionales', 'CEA-ELE2', 7, 'Electiva'),
        ('Administración de Negocios Internacionales', 'CEA-GCEX', 7, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-GEXP', 7, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-INTA', 7, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-INTM', 7, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-OPT2', 7, 'Optativa'),
        ('Administración de Negocios Internacionales', 'CEA-SENE', 7, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CSA-PRIN', 7, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-ELE3', 8, 'Electiva'),
        ('Administración de Negocios Internacionales', 'CEA-EPRS', 8, 'Humanística'),
        ('Administración de Negocios Internacionales', 'CEA-GLOB', 8, 'Humanística'),
        ('Administración de Negocios Internacionales', 'CEA-MECA', 8, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-OEF3', 8, 'Optativa'),
        ('Administración de Negocios Internacionales', 'CEA-OPT3', 8, 'Optativa'),
        ('Administración de Negocios Internacionales', 'CEA-RCYA', 8, 'Profesional'),
        ('Administración de Negocios Internacionales', 'CEA-SIGE', 8, 'Profesional'),
        ('Bacteriología', 'CSA-BIO', 1, 'Básica'),
        ('Bacteriología', 'CSA-BIOF', 1, 'Básica'),
        ('Bacteriología', 'CSA-CATU', 1, 'Humanística'),
        ('Bacteriología', 'CSA-EXOE', 1, 'Humanística'),
        ('Bacteriología', 'CSA-LGMA', 1, 'Básica'),
        ('Bacteriología', 'CSA-QUIM', 1, 'Básica'),
        ('Bacteriología', 'CSA-BIES', 2, 'Profesional'),
        ('Bacteriología', 'CSA-BIOQ', 2, 'Básica'),
        ('Bacteriología', 'CSA-CPOL', 2, 'Humanística'),
        ('Bacteriología', 'CSA-ELC1', 2, 'Electiva'),
        ('Bacteriología', 'CSA-ETBI', 2, 'Humanística'),
        ('Bacteriología', 'CSA-MFI2', 2, 'Profesional'),
        ('Bacteriología', 'CSA-SICA', 2, 'Profesional'),
        ('Bacteriología', 'CSA-BLMI', 3, 'Profesional'),
        ('Bacteriología', 'CSA-ELC2', 3, 'Electiva'),
        ('Bacteriología', 'CSA-GEN', 3, 'Básica'),
        ('Bacteriología', 'CSA-SAMY', 3, 'Humanística'),
        ('Bacteriología', 'CSA-SAP1', 3, 'Humanística'),
        ('Bacteriología', 'CSA-ELC3', 4, 'Electiva'),
        ('Bacteriología', 'CSA-HEMA', 4, 'Profesional'),
        ('Bacteriología', 'CSA-IMBA', 4, 'Profesional'),
        ('Bacteriología', 'CSA-METI', 4, 'Profesional'),
        ('Bacteriología', 'CSA-MICR', 4, 'Profesional'),
        ('Bacteriología', 'CSA-MIGE', 4, 'Profesional'),
        ('Bacteriología', 'CSA-QUCL', 4, 'Profesional'),
        ('Bacteriología', 'CSA-SAP2', 4, 'Humanística'),
        ('Bacteriología', 'CEA-OPT1', 5, 'Optativa'),
        ('Bacteriología', 'CSA-BIMO', 5, 'Profesional'),
        ('Bacteriología', 'CSA-CAMS', 5, 'Profesional'),
        ('Bacteriología', 'CSA-HECL', 5, 'Profesional'),
        ('Bacteriología', 'CSA-IMCL', 5, 'Profesional'),
        ('Bacteriología', 'CSA-PACL', 5, 'Profesional'),
        ('Bacteriología', 'CSA-QUES', 5, 'Profesional'),
        ('Bacteriología', 'CEA-OPT2', 6, 'Optativa'),
        ('Bacteriología', 'CSA-ASSS', 6, 'Profesional'),
        ('Bacteriología', 'CSA-BACL', 6, 'Profesional'),
        ('Bacteriología', 'CSA-IMBS', 6, 'Profesional'),
        ('Bacteriología', 'CSA-INTO', 6, 'Profesional'),
        ('Bacteriología', 'CSA-PRCO', 6, 'Profesional'),
        ('Bacteriología', 'CSA-VICL', 6, 'Profesional'),
        ('Bacteriología', 'CEA-OPT3', 7, 'Optativa'),
        ('Bacteriología', 'CSA-BIOT', 7, 'Básica'),
        ('Bacteriología', 'CSA-BISA', 7, 'Profesional'),
        ('Bacteriología', 'CSA-COCL', 7, 'Profesional'),
        ('Bacteriología', 'CSA-FTOX', 7, 'Profesional'),
        ('Bacteriología', 'CSA-MICL', 7, 'Profesional'),
        ('Bacteriología', 'CSA-PRIB', 7, 'Profesional'),
        ('Bacteriología', 'CSA-PRCB', 8, 'Práctico'),
        ('Bacteriología', 'CSA-TRIN', 8, 'Profesional'),
        ('Bacteriología', 'CSA-PRCL', 9, 'Práctico'),
        ('Contaduría Pública', 'CEA-CBCO', 1, 'Básica'),
        ('Contaduría Pública', 'CEA-ELE1', 1, 'Electiva'),
        ('Contaduría Pública', 'CEA-EXVE', 1, 'Humanística'),
        ('Contaduría Pública', 'CEA-FDEC', 1, 'Humanística'),
        ('Contaduría Pública', 'CEA-FDMA', 1, 'Humanística'),
        ('Contaduría Pública', 'CEA-PDCO', 1, 'Básica'),
        ('Contaduría Pública', 'CSA-CATU', 1, 'Humanística'),
        ('Contaduría Pública', 'CEA-CAL1', 2, 'Básica'),
        ('Contaduría Pública', 'CEA-CIIN', 2, 'Básica'),
        ('Contaduría Pública', 'CEA-DECO', 2, 'Profesional'),
        ('Contaduría Pública', 'CEA-ECEM', 2, 'Básica'),
        ('Contaduría Pública', 'CEA-EPMI', 2, 'Básica'),
        ('Contaduría Pública', 'CEA-FDAD', 2, 'Humanística'),
        ('Contaduría Pública', 'CEA-CEAI', 3, 'Profesional'),
        ('Contaduría Pública', 'CEA-COEN', 3, 'Profesional'),
        ('Contaduría Pública', 'CEA-DLSS', 3, 'Profesional'),
        ('Contaduría Pública', 'CEA-EMPI', 3, 'Profesional'),
        ('Contaduría Pública', 'CEA-ESDE', 3, 'Profesional'),
        ('Contaduría Pública', 'CEA-MAFI', 3, 'Básica'),
        ('Contaduría Pública', 'CEA-TECO', 3, 'Profesional'),
        ('Contaduría Pública', 'CEA-CIIF', 4, 'Profesional'),
        ('Contaduría Pública', 'CEA-COAM', 4, 'Profesional'),
        ('Contaduría Pública', 'CEA-ESIN', 4, 'Profesional'),
        ('Contaduría Pública', 'CEA-FDME', 4, 'Humanística'),
        ('Contaduría Pública', 'CEA-GEOR', 4, 'Profesional'),
        ('Contaduría Pública', 'CEA-MOIN', 4, 'Profesional'),
        ('Contaduría Pública', 'CEA-SICO', 4, 'Profesional'),
        ('Contaduría Pública', 'CEA-AFCO', 5, 'Profesional'),
        ('Contaduría Pública', 'CEA-CEFI', 5, 'Profesional'),
        ('Contaduría Pública', 'CEA-COGE', 5, 'Profesional'),
        ('Contaduría Pública', 'CEA-ELE2', 5, 'Electiva'),
        ('Contaduría Pública', 'CEA-FDNT', 5, 'Humanística'),
        ('Contaduría Pública', 'CEA-INOP', 5, 'Profesional'),
        ('Contaduría Pública', 'CEA-ADFI', 6, 'Profesional'),
        ('Contaduría Pública', 'CEA-AUAP', 6, 'Profesional'),
        ('Contaduría Pública', 'CEA-CONG', 6, 'Profesional'),
        ('Contaduría Pública', 'CEA-IMRE', 6, 'Profesional'),
        ('Contaduría Pública', 'CEA-OPT1', 6, 'Optativa'),
        ('Contaduría Pública', 'CEA-PREM', 6, 'Profesional'),
        ('Contaduría Pública', 'CEA-COFP', 7, 'Profesional'),
        ('Contaduría Pública', 'CEA-FGPR', 7, 'Profesional'),
        ('Contaduría Pública', 'CEA-FICO', 7, 'Profesional'),
        ('Contaduría Pública', 'CEA-IVYR', 7, 'Profesional'),
        ('Contaduría Pública', 'CEA-OPT2', 7, 'Optativa'),
        ('Contaduría Pública', 'CEA-REFI', 7, 'Profesional'),
        ('Contaduría Pública', 'CEA-AUSI', 8, 'Profesional'),
        ('Contaduría Pública', 'CEA-ELE3', 8, 'Electiva'),
        ('Contaduría Pública', 'CEA-ITPT', 8, 'Profesional'),
        ('Contaduría Pública', 'CEA-OPT3', 8, 'Optativa'),
        ('Contaduría Pública', 'CEA-SIGE', 8, 'Profesional'),
        ('Contaduría Pública', 'ING-ETPR', 8, 'Humanística'),
        ('Derecho', 'CSA-CATU', 1, 'Humanística'),
        ('Derecho', 'DER-DERO', 1, 'Básica'),
        ('Derecho', 'DER-HACO', 1, 'Humanística'),
        ('Derecho', 'DER-HIFL', 1, 'Humanística'),
        ('Derecho', 'DER-INDE', 1, 'Profesional'),
        ('Derecho', 'DER-TEEC', 1, 'Básica'),
        ('Derecho', 'DER-TEES', 1, 'Básica'),
        ('Derecho', 'DER-CGPE', 2, 'Básica'),
        ('Derecho', 'DER-CIPL', 2, 'Básica'),
        ('Derecho', 'DER-DHDH', 2, 'Básica'),
        ('Derecho', 'DER-ECCO', 2, 'Básica'),
        ('Derecho', 'DER-ETI1', 2, 'Humanística'),
        ('Derecho', 'DER-SGJU', 2, 'Básica'),
        ('Derecho', 'DER-TECO2', 2, 'Básica'),
        ('Derecho', 'CEA-ELE2', 3, 'Electiva'),
        ('Derecho', 'DER-BIEN', 3, 'Profesional'),
        ('Derecho', 'DER-COCO', 3, 'Profesional'),
        ('Derecho', 'DER-INI1', 3, 'Profesional'),
        ('Derecho', 'DER-LGJU', 3, 'Profesional'),
        ('Derecho', 'DER-TEDE', 3, 'Básica'),
        ('Derecho', 'CEA-ELE3', 4, 'Electiva'),
        ('Derecho', 'DER-DIPU', 4, 'Profesional'),
        ('Derecho', 'DER-ELE4', 4, 'Electiva'),
        ('Derecho', 'DER-INI2', 4, 'Profesional'),
        ('Derecho', 'DER-LAIP', 4, 'Básica'),
        ('Derecho', 'DER-SACO', 4, 'Humanística'),
        ('Derecho', 'DER-TGPR', 4, 'Profesional'),
        ('Derecho', 'DER-TPB1', 4, 'Profesional'),
        ('Derecho', 'DER-ADGE', 5, 'Profesional'),
        ('Derecho', 'DER-DIPR', 5, 'Profesional'),
        ('Derecho', 'DER-ELE5', 5, 'Electiva'),
        ('Derecho', 'DER-HEJR', 5, 'Profesional'),
        ('Derecho', 'DER-INI3', 5, 'Profesional'),
        ('Derecho', 'DER-OBLI', 5, 'Profesional'),
        ('Derecho', 'DER-PPE1', 5, 'Profesional'),
        ('Derecho', 'DER-TPB2', 5, 'Profesional'),
        ('Derecho', 'DER-ADCO', 6, 'Profesional'),
        ('Derecho', 'DER-ARJR', 6, 'Profesional'),
        ('Derecho', 'DER-DCGE', 6, 'Profesional'),
        ('Derecho', 'DER-INI4', 6, 'Profesional'),
        ('Derecho', 'DER-LACO', 6, 'Básica'),
        ('Derecho', 'DER-PCGE', 6, 'Profesional'),
        ('Derecho', 'DER-PPE2', 6, 'Profesional'),
        ('Derecho', 'DER-CJU1', 7, 'Práctico'),
        ('Derecho', 'DER-CONT', 7, 'Profesional'),
        ('Derecho', 'DER-CRPC', 7, 'Profesional'),
        ('Derecho', 'DER-FIAD', 7, 'Profesional'),
        ('Derecho', 'DER-FIDE', 7, 'Profesional'),
        ('Derecho', 'DER-PROB', 7, 'Profesional'),
        ('Derecho', 'DER-TVAL', 7, 'Básica'),
        ('Derecho', 'DER-CJU2', 8, 'Práctico'),
        ('Derecho', 'DER-CRCF', 8, 'Profesional'),
        ('Derecho', 'DER-LAAD', 8, 'Básica'),
        ('Derecho', 'DER-PAD1', 8, 'Profesional'),
        ('Derecho', 'DER-PCEF', 8, 'Profesional'),
        ('Derecho', 'DER-PLAB', 8, 'Básica'),
        ('Derecho', 'DER-SESO', 8, 'Profesional'),
        ('Derecho', 'CEA-OPT1', 9, 'Optativa'),
        ('Derecho', 'CEA-OPT2', 9, 'Optativa'),
        ('Derecho', 'DER-CJU3', 9, 'Práctico'),
        ('Derecho', 'DER-JUCO', 9, 'Profesional'),
        ('Derecho', 'DER-PAD2', 9, 'Profesional'),
        ('Derecho', 'DER-SUCE', 9, 'Profesional'),
        ('Derecho', 'CEA-OPT3', 10, 'Optativa'),
        ('Derecho', 'DER-CJU4', 10, 'Práctico'),
        ('Derecho', 'DER-DEAM', 10, 'Profesional'),
        ('Derecho', 'DER-ETI2', 10, 'Humanística'),
        ('Derecho', 'DER-FIPU', 10, 'Profesional'),
        ('Derecho', 'DER-OPT4', 10, 'Optativa'),
        ('Derecho', 'DER-OPT5', 10, 'Optativa'),
        ('Derecho', 'DER-RECI', 10, 'Profesional'),
        ('Fisioterapia', 'CSA-BIHI', 1, 'Profesional'),
        ('Fisioterapia', 'CSA-BIOF', 1, 'Básica'),
        ('Fisioterapia', 'CSA-CATU', 1, 'Humanística'),
        ('Fisioterapia', 'CSA-FART', 1, 'Profesional'),
        ('Fisioterapia', 'CSA-INFI', 1, 'Profesional'),
        ('Fisioterapia', 'CSA-LGMA', 1, 'Básica'),
        ('Fisioterapia', 'CSA-MFI1', 1, 'Profesional'),
        ('Fisioterapia', 'CSA-SAYU', 1, 'Humanística'),
        ('Fisioterapia', 'CSA-SCAN', 1, 'Profesional'),
        ('Fisioterapia', 'CSA-BIOM', 2, 'Básica'),
        ('Fisioterapia', 'CSA-BIOQ', 2, 'Básica'),
        ('Fisioterapia', 'CSA-ELC1', 2, 'Electiva'),
        ('Fisioterapia', 'CSA-FIEJ', 2, 'Profesional'),
        ('Fisioterapia', 'CSA-METI', 2, 'Profesional'),
        ('Fisioterapia', 'CSA-MFI2', 2, 'Profesional'),
        ('Fisioterapia', 'CSA-PATO', 2, 'Básica'),
        ('Fisioterapia', 'CSA-PSEV', 2, 'Profesional'),
        ('Fisioterapia', 'CSA-BIES', 3, 'Profesional'),
        ('Fisioterapia', 'CSA-CIPA', 3, 'Profesional'),
        ('Fisioterapia', 'CSA-EVDI', 3, 'Profesional'),
        ('Fisioterapia', 'CSA-IFI1', 3, 'Profesional'),
        ('Fisioterapia', 'CSA-NEMO', 3, 'Profesional'),
        ('Fisioterapia', 'CSA-PREJ', 3, 'Profesional'),
        ('Fisioterapia', 'CSA-PSSA', 3, 'Profesional'),
        ('Fisioterapia', 'CSA-CAPM', 4, 'Profesional'),
        ('Fisioterapia', 'CSA-CPOL', 4, 'Humanística'),
        ('Fisioterapia', 'CSA-DISC', 4, 'Profesional'),
        ('Fisioterapia', 'CSA-ELC2', 4, 'Electiva'),
        ('Fisioterapia', 'CSA-EPID', 4, 'Básica'),
        ('Fisioterapia', 'CSA-FAFI', 4, 'Profesional'),
        ('Fisioterapia', 'CSA-IFI2', 4, 'Profesional'),
        ('Fisioterapia', 'CSA-MOFI', 4, 'Profesional'),
        ('Fisioterapia', 'CSA-ADSA', 5, 'Profesional'),
        ('Fisioterapia', 'CSA-EPCI', 5, 'Profesional'),
        ('Fisioterapia', 'CSA-ETBI', 5, 'Humanística'),
        ('Fisioterapia', 'CSA-IFI3', 5, 'Profesional'),
        ('Fisioterapia', 'CSA-OCMC', 5, 'Profesional'),
        ('Fisioterapia', 'CSA-SAPU', 5, 'Humanística'),
        ('Fisioterapia', 'CSA-ELC3', 6, 'Electiva'),
        ('Fisioterapia', 'CSA-EPI1', 6, 'Electiva'),
        ('Fisioterapia', 'CSA-PRFO', 6, 'Práctico'),
        ('Fisioterapia', 'CSA-PRIN', 6, 'Profesional'),
        ('Fisioterapia', 'CSA-EPI2', 7, 'Electiva'),
        ('Fisioterapia', 'CSA-PRI2', 7, 'Profesional'),
        ('Fisioterapia', 'CSA-ELC4', 8, 'Electiva'),
        ('Fisioterapia', 'CSA-EPI3', 8, 'Electiva'),
        ('Fisioterapia', 'CSA-PRI3', 8, 'Profesional'),
        ('Fisioterapia', 'CSA-PROP', 8, 'Práctico'),
        ('Ingeniería de Sistemas', 'CSA-CATU', 1, 'Humanística'),
        ('Ingeniería de Sistemas', 'ING-CALD', 1, 'Básica'),
        ('Ingeniería de Sistemas', 'ING-CPAC', 1, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-FIME', 1, 'Básica'),
        ('Ingeniería de Sistemas', 'ING-INGE', 1, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-LGAL', 1, 'Básica'),
        ('Ingeniería de Sistemas', 'ING-LGMA2', 1, 'Básica'),
        ('Ingeniería de Sistemas', 'CEA-ELE1', 2, 'Electiva'),
        ('Ingeniería de Sistemas', 'ING-ALGE', 2, 'Básica'),
        ('Ingeniería de Sistemas', 'ING-CALI', 2, 'Básica'),
        ('Ingeniería de Sistemas', 'ING-ELDI', 2, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-EMLA', 2, 'Básica'),
        ('Ingeniería de Sistemas', 'ING-FDPR', 2, 'Humanística'),
        ('Ingeniería de Sistemas', 'ING-PESI', 2, 'Práctico'),
        ('Ingeniería de Sistemas', 'ING-ARCO', 3, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-CMVC', 3, 'Básica'),
        ('Ingeniería de Sistemas', 'ING-DSIN', 3, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-ESDA', 3, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-ISW1', 3, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-PRED', 3, 'Básica'),
        ('Ingeniería de Sistemas', 'CEA-ELE2', 4, 'Electiva'),
        ('Ingeniería de Sistemas', 'CSA-CPOL', 4, 'Humanística'),
        ('Ingeniería de Sistemas', 'ING-CASO', 4, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-ECDI', 4, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-FBDA', 4, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-ISW2', 4, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-PRG1', 4, 'Profesional'),
        ('Ingeniería de Sistemas', 'CEA-FDEC', 5, 'Humanística'),
        ('Ingeniería de Sistemas', 'ING-ISW3', 5, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-MADE', 5, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-PRG2', 5, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-SBDA', 5, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-SIOP', 5, 'Profesional'),
        ('Ingeniería de Sistemas', 'CEA-ELE3', 6, 'Electiva'),
        ('Ingeniería de Sistemas', 'CEA-OPT1', 6, 'Optativa'),
        ('Ingeniería de Sistemas', 'ING-ARIN', 6, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-FEPR', 6, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-PRLI', 6, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-PRWE', 6, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-RECO', 6, 'Profesional'),
        ('Ingeniería de Sistemas', 'CEA-OPT2', 7, 'Optativa'),
        ('Ingeniería de Sistemas', 'CSA-METI', 7, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-ETPR', 7, 'Humanística'),
        ('Ingeniería de Sistemas', 'ING-GPIN', 7, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-INAR', 7, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-PRMO', 7, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-SEIN', 7, 'Profesional'),
        ('Ingeniería de Sistemas', 'CEA-OPT3', 8, 'Optativa'),
        ('Ingeniería de Sistemas', 'ING-AREM', 8, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-GERE', 8, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-INAP', 8, 'Profesional'),
        ('Ingeniería de Sistemas', 'ING-PREM2', 8, 'Práctico'),
        ('Ingeniería de Sistemas', 'ING-SIGE2', 8, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-BIHI', 1, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-BIOF', 1, 'Básica'),
        ('Instrumentación Quirúrgica', 'CSA-CATU', 1, 'Humanística'),
        ('Instrumentación Quirúrgica', 'CSA-CCI1', 1, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-ININ', 1, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-MFI1', 1, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-QUIM', 1, 'Básica'),
        ('Instrumentación Quirúrgica', 'CSA-SSSC', 1, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-BEIN', 2, 'Básica'),
        ('Instrumentación Quirúrgica', 'CSA-BIOQ', 2, 'Básica'),
        ('Instrumentación Quirúrgica', 'CSA-CCI2', 2, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-EGDI', 2, 'Humanística'),
        ('Instrumentación Quirúrgica', 'CSA-FDPS', 2, 'Humanística'),
        ('Instrumentación Quirúrgica', 'CSA-MFI2', 2, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-MICR', 2, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-CIPS', 3, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-CUBS', 3, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-ELC1', 3, 'Electiva'),
        ('Instrumentación Quirúrgica', 'CSA-FRAN', 3, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-ICEP', 3, 'Básica'),
        ('Instrumentación Quirúrgica', 'CSA-PAS1', 3, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PATO', 3, 'Básica'),
        ('Instrumentación Quirúrgica', 'CSA-SCAN', 3, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-CONA', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-CPOL', 4, 'Humanística'),
        ('Instrumentación Quirúrgica', 'CSA-METI', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PAS2', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PQGO', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PQGP', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PQUR', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-SSET', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-CASS', 5, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-INTE', 5, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PQNE', 5, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PQOR', 5, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PRH1', 5, 'Práctico'),
        ('Instrumentación Quirúrgica', 'CSA-ADM1', 6, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-EPI1', 6, 'Electiva'),
        ('Instrumentación Quirúrgica', 'CSA-PQCM', 6, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PQCP', 6, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PQOF', 6, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PRH2', 6, 'Práctico'),
        ('Instrumentación Quirúrgica', 'CSA-SAPU', 6, 'Humanística'),
        ('Instrumentación Quirúrgica', 'CSA-ADM2', 7, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-EPI2', 7, 'Electiva'),
        ('Instrumentación Quirúrgica', 'CSA-PQCV', 7, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PQOT', 7, 'Profesional'),
        ('Instrumentación Quirúrgica', 'CSA-PRH3', 7, 'Práctico'),
        ('Instrumentación Quirúrgica', 'CSA-PRAD', 8, 'Práctico'),
        ('Instrumentación Quirúrgica', 'CSA-PRH4', 8, 'Práctico'),
        ('Instrumentación Quirúrgica', 'CSA-SAPC', 8, 'Humanística'),
        ('Medicina', 'CSA-BIO', 1, 'Básica'),
        ('Medicina', 'CSA-BIOF', 1, 'Básica'),
        ('Medicina', 'CSA-CATU', 1, 'Humanística'),
        ('Medicina', 'CSA-EXOE', 1, 'Humanística'),
        ('Medicina', 'CSA-QUIM', 1, 'Básica'),
        ('Medicina', 'CSA-SCAN', 1, 'Profesional'),
        ('Medicina', 'CSA-BIOQ', 2, 'Básica'),
        ('Medicina', 'CSA-ELCM', 2, 'Electiva'),
        ('Medicina', 'CSA-METI', 2, 'Profesional'),
        ('Medicina', 'CSA-MOR1', 2, 'Profesional'),
        ('Medicina', 'CSA-BIMO', 3, 'Profesional'),
        ('Medicina', 'CSA-MOR2', 3, 'Profesional'),
        ('Medicina', 'CSA-PSDE', 3, 'Profesional'),
        ('Medicina', 'CSA-SAF1', 3, 'Humanística'),
        ('Medicina', 'CSA-EPBA', 4, 'Profesional'),
        ('Medicina', 'CSA-FISIO', 4, 'Básica'),
        ('Medicina', 'CSA-INMU', 4, 'Básica'),
        ('Medicina', 'CSA-SAF2', 4, 'Humanística'),
        ('Medicina', 'CSA-ETME', 5, 'Humanística'),
        ('Medicina', 'CSA-FTBA', 5, 'Profesional'),
        ('Medicina', 'CSA-MICR', 5, 'Profesional'),
        ('Medicina', 'CSA-SAPU', 5, 'Humanística'),
        ('Medicina', 'CSA-BIET', 6, 'Profesional'),
        ('Medicina', 'CSA-FATC', 6, 'Profesional'),
        ('Medicina', 'CSA-GECL', 6, 'Profesional'),
        ('Medicina', 'CSA-PSCP', 6, 'Profesional'),
        ('Medicina', 'CSA-SEMI', 6, 'Profesional'),
        ('Medicina', 'CSA-CPOL', 7, 'Humanística'),
        ('Medicina', 'CSA-EPCL', 7, 'Profesional'),
        ('Medicina', 'CSA-MEIN', 7, 'Profesional'),
        ('Medicina', 'CSA-PSIQ', 7, 'Profesional'),
        ('Medicina', 'CSA-CIRG', 8, 'Práctico'),
        ('Medicina', 'CSA-EPR1', 8, 'Electiva'),
        ('Medicina', 'CSA-ESQU', 8, 'Profesional'),
        ('Medicina', 'CSA-SSTR', 8, 'Profesional'),
        ('Medicina', 'CSA-APSI', 9, 'Profesional'),
        ('Medicina', 'CSA-EPR2', 9, 'Electiva'),
        ('Medicina', 'CSA-PEDI', 9, 'Práctico'),
        ('Medicina', 'CSA-PRIN', 9, 'Profesional'),
        ('Medicina', 'CSA-ADSI', 10, 'Profesional'),
        ('Medicina', 'CSA-GIOB', 10, 'Profesional'),
        ('Medicina', 'CSA-MELE', 10, 'Profesional'),
        ('Medicina', 'CSA-TRGR', 10, 'Profesional'),
        ('Microbiología', 'CEA-ELE1', 1, 'Electiva'),
        ('Microbiología', 'CSA-BIO', 1, 'Básica'),
        ('Microbiología', 'CSA-CATU', 1, 'Humanística'),
        ('Microbiología', 'CSA-EXOE', 1, 'Humanística'),
        ('Microbiología', 'CSA-FIS', 1, 'Básica'),
        ('Microbiología', 'CSA-HCIE', 1, 'Profesional'),
        ('Microbiología', 'CSA-MAT', 1, 'Básica'),
        ('Microbiología', 'CSA-QUIM', 1, 'Básica'),
        ('Microbiología', 'CEA-CALC', 2, 'Básica'),
        ('Microbiología', 'CSA-BIET', 2, 'Profesional'),
        ('Microbiología', 'CSA-BIOQ', 2, 'Básica'),
        ('Microbiología', 'CSA-CPOL', 2, 'Humanística'),
        ('Microbiología', 'CSA-FPHY', 2, 'Práctico'),
        ('Microbiología', 'CSA-GEN', 2, 'Básica'),
        ('Microbiología', 'CSA-METI', 2, 'Profesional'),
        ('Microbiología', 'CEA-ELE2', 3, 'Electiva'),
        ('Microbiología', 'CSA-BIMI', 3, 'Profesional'),
        ('Microbiología', 'CSA-BIMO', 3, 'Profesional'),
        ('Microbiología', 'CSA-BQMI', 3, 'Básica'),
        ('Microbiología', 'CSA-ESTA', 3, 'Profesional'),
        ('Microbiología', 'CSA-FPAN', 3, 'Profesional'),
        ('Microbiología', 'CSA-AFIQ', 4, 'Profesional'),
        ('Microbiología', 'CSA-BINF', 4, 'Profesional'),
        ('Microbiología', 'CSA-EMPE', 4, 'Profesional'),
        ('Microbiología', 'CSA-FPVE', 4, 'Profesional'),
        ('Microbiología', 'CSA-INMU', 4, 'Básica'),
        ('Microbiología', 'CSA-MICR', 4, 'Profesional'),
        ('Microbiología', 'CSA-DIEX', 5, 'Profesional'),
        ('Microbiología', 'CSA-ECMI', 5, 'Profesional'),
        ('Microbiología', 'CSA-MIAM', 5, 'Profesional'),
        ('Microbiología', 'CSA-MIIN', 5, 'Profesional'),
        ('Microbiología', 'CSA-PRIN', 5, 'Profesional'),
        ('Microbiología', 'CSA-TOXC', 5, 'Profesional'),
        ('Microbiología', 'CEA-OPT1', 6, 'Optativa'),
        ('Microbiología', 'CSA-BIOT', 6, 'Básica'),
        ('Microbiología', 'CSA-MIAM2', 6, 'Profesional'),
        ('Microbiología', 'CSA-MISU', 6, 'Profesional'),
        ('Microbiología', 'CSA-SAPU', 6, 'Humanística'),
        ('Microbiología', 'CSA-TRIN', 6, 'Profesional'),
        ('Microbiología', 'CEA-ELE3', 7, 'Electiva'),
        ('Microbiología', 'CEA-OPT2', 7, 'Optativa'),
        ('Microbiología', 'CEA-OPT3', 7, 'Optativa'),
        ('Microbiología', 'CSA-ADMI', 7, 'Profesional'),
        ('Microbiología', 'CSA-MIPR', 7, 'Profesional'),
        ('Microbiología', 'CSA-PRIN2', 7, 'Profesional'),
        ('Microbiología', 'CSA-PRPR', 8, 'Práctico'),
    ]
    
    created_count = 0
    updated_count = 0
    skipped_count = 0
    
    for nombre_programa, codigo_asignatura, semestre, componente_str in relaciones_data:
        try:
            programa = Programa.objects.get(nombre=nombre_programa)
            asignatura = Asignatura.objects.get(codigo=codigo_asignatura)
            
            componente = componentes_map.get(componente_str, 'Profesional')
            
            relacion, created = AsignaturaPrograma.objects.update_or_create(
                programa=programa,
                asignatura=asignatura,
                defaults={
                    'semestre': semestre,
                    'componente_formativo': componente
                }
            )
            
            if created:
                created_count += 1
            else:
                updated_count += 1
                
        except Programa.DoesNotExist:
            skipped_count += 1
            stdout.write(style.WARNING(f'      ! Programa no encontrado: {nombre_programa}'))
        except Asignatura.DoesNotExist:
            skipped_count += 1
            stdout.write(style.WARNING(f'      ! Asignatura no encontrada: {codigo_asignatura}'))
    
    total = len(relaciones_data)
    stdout.write(style.SUCCESS(f'    ✓ Relaciones procesadas: {created_count} nuevas, {updated_count} actualizadas, {skipped_count} omitidas, {total} totales'))
