"""
Seeder de asignaturas de todos los programas.
"""

from asignaturas.models import Asignatura


def create_asignaturas(stdout, style):
    """Crear todas las asignaturas de todos los programas"""
    stdout.write('  → Creando asignaturas...')
    stdout.write('     Este proceso puede tomar unos segundos...')
    
    asignaturas_data = _get_all_asignaturas()
    
    created_count = 0
    updated_count = 0
    
    for nombre, codigo, creditos, tipo_str, horas in asignaturas_data:
        # Mapear tipo_str al valor del modelo
        # El campo 'tipo' en Asignatura solo acepta: 'teórica', 'práctica', 'mixta'
        tipo_map = {
            'Básica': 'teórica',
            'Profesional': 'teórica',
            'Humanística': 'teórica',
            'Práctico': 'práctica',
            'Optativa': 'teórica',
            'Electiva': 'teórica',
        }
        tipo = tipo_map.get(tipo_str, 'teórica')
        
        asignatura, created = Asignatura.objects.update_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'creditos': creditos,
                'tipo': tipo,
                'horas': horas
            }
        )
        
        if created:
            created_count += 1
        else:
            updated_count += 1
    
    total = len(asignaturas_data)
    stdout.write(style.SUCCESS(f'    ✓ Asignaturas procesadas: {created_count} nuevas, {updated_count} actualizadas, {total} totales'))


def _get_all_asignaturas():
    """Retorna la lista completa de asignaturas de todos los programas"""
    # Formato: (nombre, código, créditos, tipo, horas)
    # tipo puede ser: 'teórica', 'práctica', 'mixta'
    return [
        ('Administración', 'CSA-ADMI', 3, 'teórica', 144),
        ('Administración Financiera', 'CEA-ADFI', 3, 'teórica', 144),
        ('Administración I', 'CSA-ADM1', 3, 'teórica', 144),
        ('Administración II', 'CSA-ADM2', 3, 'teórica', 144),
        ('Administración en Salud', 'CSA-ADSA', 3, 'teórica', 144),
        ('Administración en Salud II', 'CSA-ADSI', 3, 'teórica', 144),
        ('Administración y Planeación en Salud I', 'CSA-APSI', 3, 'teórica', 144),
        ('Administración y SSS', 'CSA-ASSS', 3, 'teórica', 144),
        ('Administrativo Colombiano', 'DER-ADCO', 3, 'teórica', 144),
        ('Administrativo General', 'DER-ADGE', 3, 'teórica', 144),
        ('Análisis Físico-Químico', 'CSA-AFIQ', 3, 'teórica', 144),
        ('Argumentación Jurídica', 'DER-ARJR', 3, 'teórica', 144),
        ('Arquitectura Empresarial', 'ING-AREM', 3, 'teórica', 144),
        ('Arquitectura de Computadores', 'ING-ARCO', 3, 'teórica', 144),
        ('Arquitectura de Información', 'ING-ARIN', 3, 'teórica', 144),
        ('Aseguramiento y Fundamentos de Control', 'CEA-AFCO', 3, 'teórica', 144),
        ('Auditoría Aplicada', 'CEA-AUAP', 3, 'teórica', 144),
        ('Auditoría de Sistemas', 'CEA-AUSI', 3, 'teórica', 144),
        ('Bacteriología Clínica', 'CSA-BACL', 3, 'teórica', 144),
        ('Bienes', 'DER-BIEN', 3, 'teórica', 144),
        ('Bioestadística', 'CSA-BIES', 3, 'teórica', 144),
        ('Bioestadística e Informática', 'CSA-BEIN', 3, 'teórica', 144),
        ('Biofísica', 'CSA-BIOF', 3, 'teórica', 144),
        ('Bioinformática', 'CSA-BINF', 3, 'teórica', 144),
        ('Biología', 'CSA-BIO', 3, 'teórica', 144),
        ('Biología Molecular', 'CSA-BIMO', 3, 'teórica', 144),
        ('Biología de Microorganismos', 'CSA-BIMI', 3, 'teórica', 144),
        ('Biología de los Microorganismos', 'CSA-BLMI', 3, 'teórica', 144),
        ('Biología e Histología', 'CSA-BIHI', 3, 'teórica', 144),
        ('Biomecánica', 'CSA-BIOM', 3, 'teórica', 144),
        ('Bioquímica', 'CSA-BIOQ', 3, 'teórica', 144),
        ('Bioquímica Microbiana', 'CSA-BQMI', 3, 'teórica', 144),
        ('Biotecnología', 'CSA-BIOT', 3, 'teórica', 144),
        ('Biotecnología de la Salud', 'CSA-BISA', 3, 'teórica', 144),
        ('Bioética', 'CSA-BIET', 3, 'teórica', 144),
        ('Curso Francés', 'CSA-CFRN', 3, 'teórica', 144),
        ('Calidad Microbiológica y Sanitaria', 'CSA-CAMS', 3, 'teórica', 144),
        ('Calidad en Servicios de Salud', 'CSA-CASS', 3, 'teórica', 144),
        ('Ciclo Básico Contable', 'CEA-CBCO', 3, 'teórica', 144),
        ('Ciclo de Egresos y Adm. de Inventarios', 'CEA-CEAI', 3, 'teórica', 144),
        ('Ciclo de Estados Financieros', 'CEA-CEFI', 3, 'teórica', 144),
        ('Ciclo de Ingresos', 'CEA-CIIN', 3, 'teórica', 144),
        ('Ciclo de Inversiones y Financiación', 'CEA-CIIF', 3, 'teórica', 144),
        ('Ciencia Política', 'DER-CIPL', 3, 'teórica', 144),
        ('Cinesiopatología', 'CSA-CIPA', 3, 'teórica', 144),
        ('Cirugía', 'CSA-CIRU', 5, 'práctica', 240),
        ('Cirugía General', 'CSA-CIRG', 5, 'práctica', 240),
        ('Civil General y Personas', 'DER-CGPE', 3, 'teórica', 144),
        ('Comercio y Negocios Globales', 'CEA-CONG', 3, 'teórica', 144),
        ('Competencias Comunicativas I', 'CSA-CCI1', 3, 'teórica', 144),
        ('Competencias Comunicativas II', 'CSA-CCI2', 3, 'teórica', 144),
        ('Competencias de Aprendizaje y Comunicación', 'ING-CPAC', 3, 'teórica', 144),
        ('Constitucional Colombiano', 'DER-COCO', 3, 'teórica', 144),
        ('Constitución Nacional', 'CSA-CONA', 3, 'teórica', 144),
        ('Constitución Política', 'CSA-CPOL', 3, 'teórica', 144),
        ('Consultorio Jurídico I', 'DER-CJU1', 5, 'práctica', 240),
        ('Consultorio Jurídico II', 'DER-CJU2', 5, 'práctica', 240),
        ('Consultorio Jurídico III', 'DER-CJU3', 5, 'práctica', 240),
        ('Consultorio Jurídico IV', 'DER-CJU4', 5, 'práctica', 240),
        ('Contabilidad Ambiental', 'CEA-COAM', 3, 'teórica', 144),
        ('Contabilidad Financiera', 'CEA-COFI', 3, 'teórica', 144),
        ('Contabilidad y Finanzas Públicas', 'CEA-COFP', 3, 'teórica', 144),
        ('Contratos', 'DER-CONT', 3, 'teórica', 144),
        ('Control de Infecciones y Promoción de la Salud', 'CSA-CIPS', 3, 'teórica', 144),
        ('Control y Aprendizaje Motor', 'CSA-CAPM', 3, 'teórica', 144),
        ('Correlación Clínica', 'CSA-COCL', 3, 'teórica', 144),
        ('Costos Gerenciales', 'CEA-COGE', 3, 'teórica', 144),
        ('Coyuntura Económica Internacional', 'CEA-COEI', 3, 'teórica', 144),
        ('Coyuntura Económica Nacional', 'CEA-COEN', 3, 'teórica', 144),
        ('Criminalística y Ciencias Forenses', 'DER-CRCF', 3, 'teórica', 144),
        ('Criminología y Política Criminal', 'DER-CRPC', 3, 'teórica', 144),
        ('Cuidados Básicos en Salud', 'CSA-CUBS', 3, 'teórica', 144),
        ('Cálculo', 'CEA-CALC', 3, 'teórica', 144),
        ('Cálculo Diferencial', 'ING-CALD', 3, 'teórica', 144),
        ('Cálculo I', 'CEA-CAL1', 3, 'teórica', 144),
        ('Cálculo Integral', 'ING-CALI', 3, 'teórica', 144),
        ('Cálculo Multivariado y Vectorial', 'ING-CMVC', 3, 'teórica', 144),
        ('Cátedra Unilibrista', 'CSA-CATU', 3, 'teórica', 144),
        ('Cátedra de Sostenibilidad', 'ING-CASO', 3, 'teórica', 144),
        ('C.A.S.A', 'CASA-CASA', 3, 'teórica', 144),
        ('Derecho Ambiental', 'DER-DEAM', 3, 'teórica', 144),
        ('Derecho Comercial', 'CEA-DECO', 3, 'teórica', 144),
        ('Derecho Comercial General', 'DER-DCGE', 3, 'teórica', 144),
        ('Derecho Comercial Internacional', 'CEA-DCIN', 3, 'teórica', 144),
        ('Derecho Internacional Privado', 'DER-DIPR', 3, 'teórica', 144),
        ('Derecho Internacional Público', 'DER-DIPU', 3, 'teórica', 144),
        ('Derecho Laboral y Seguridad Social', 'CEA-DLSS', 3, 'teórica', 144),
        ('Derecho Romano', 'DER-DERO', 3, 'teórica', 144),
        ('Derechos Humanos y DIH', 'DER-DHDH', 3, 'teórica', 144),
        ('Desarrollo e Innovación de las Organizaciones', 'CEA-DINO', 3, 'teórica', 144),
        ('Dirección y Liderazgo', 'CEA-DILI', 3, 'teórica', 144),
        ('Discapacidad', 'CSA-DISC', 3, 'teórica', 144),
        ('Diseño Experimental', 'CSA-DIEX', 3, 'teórica', 144),
        ('Diseño en Ingeniería', 'ING-DSIN', 3, 'teórica', 144),
        ('Ecología Microbiana', 'CSA-ECMI', 3, 'teórica', 144),
        ('Economía Colombiana', 'DER-ECCO', 3, 'teórica', 144),
        ('Economía de Empresa', 'CEA-ECEM', 3, 'teórica', 144),
        ('Ecuaciones Diferenciales', 'ING-ECDI', 3, 'teórica', 144),
        ('Elect. Básica de Ingeniería III (Inv. de Operaciones)', 'ING-EBI3', 3, 'teórica', 144),
        ('Electiva II (Emprendimiento y Liderazgo)', 'ING-ELLE', 2, 'teórica', 96),
        ('Electiva Complementaria (Medicina)', 'CSA-ELCM', 2, 'teórica', 96),
        ('Electiva Complementaria I', 'CSA-ELC1', 2, 'teórica', 96),
        ('Electiva Complementaria II', 'CSA-ELC2', 2, 'teórica', 96),
        ('Electiva Complementaria III', 'CSA-ELC3', 2, 'teórica', 96),
        ('Electiva Complementaria IV', 'CSA-ELC4', 2, 'teórica', 96),
        ('Electiva profesional IV (Creación de Empresas)', 'CSA-EPIV', 2, 'teórica', 96),
        ('ELECTIVA I COMPETENCIA Y CULTURA CIUDADANA', 'CEA-ELE1', 2, 'teórica', 96),
        ('Electiva I: ENGLISH SABER-PROTRAINING WORKSHOP', 'CSA-ELE1', 2, 'teórica', 96),
        ('Electiva II', 'CEA-ELE2', 2, 'teórica', 96),
        ('Electiva III', 'CEA-ELE3', 2, 'teórica', 96),
        ('Electiva III', 'ING-ELE3', 2, 'teórica', 96),
        ('Electiva IV', 'DER-ELE4', 2, 'teórica', 96),
        ('Electiva Profesional I', 'CSA-EPR1', 2, 'teórica', 96),
        ('Electiva Profesional II', 'CSA-EPR2', 2, 'teórica', 96),
        ('Electiva Profesional II', 'ING-EPR2', 2, 'teórica', 96),
        ('Electiva Profesional III', 'CSA-EPR3', 2, 'teórica', 96),
        ('Electiva de profundización (B): Diagnóstico Forense', 'CSA-EDPF', 2, 'teórica', 96),
        ('Electiva V', 'DER-ELE5', 2, 'teórica', 96),
        ('Electiva de Profundización I', 'CSA-EPI1', 2, 'teórica', 96),
        ('Electiva de Profundización II', 'CSA-EPI2', 2, 'teórica', 96),
        ('Electiva de Profundización III', 'CSA-EPI3', 2, 'teórica', 96),
        ('Electricidad, Magnetismo y Laboratorio', 'ING-EMLA', 3, 'teórica', 144),
        ('Electrónica Digital', 'ING-ELDI', 3, 'teórica', 144),
        ('Emprendimiento e Innovación', 'CEA-EMPI', 3, 'teórica', 144),
        ('Empresarismo y Emprendimiento', 'CSA-EMPE', 3, 'teórica', 144),
        ('Epidemiología', 'CSA-EPID', 3, 'teórica', 144),
        ('Epidemiología Básica', 'CSA-EPBA', 3, 'teórica', 144),
        ('Epidemiología Clínica', 'CSA-EPCL', 3, 'teórica', 144),
        ('Epistemología de las Ciencias', 'CSA-EPCI', 3, 'teórica', 144),
        ('Epistemología y Metodología de la Investigación', 'CEA-EPMI', 3, 'teórica', 144),
        ('Especialidades Quirúrgicas', 'CSA-ESQU', 3, 'teórica', 144),
        ('Estadística', 'CSA-ESTA', 3, 'teórica', 144),
        ('Estadística Descriptiva', 'CEA-ESDE', 3, 'teórica', 144),
        ('Estadística Inferencial', 'CEA-ESIN', 3, 'teórica', 144),
        ('Estructuras de Datos', 'ING-ESDA', 3, 'teórica', 144),
        ('Evaluación y Diagnóstico', 'CSA-EVDI', 3, 'teórica', 144),
        ('Expresión Oral y Escrita', 'CSA-EXOE', 3, 'teórica', 144),
        ('Expresión Verbal y Escrita', 'CEA-EXVE', 3, 'teórica', 144),
        ('Extramural', 'CSA-EXTR', 3, 'teórica', 144),
        ('Familia, Infancia y Adolescencia', 'DER-FIAD', 3, 'teórica', 144),
        ('Farmacología Aplicada y Toxicología Clínica', 'CSA-FATC', 3, 'teórica', 144),
        ('Farmacología en Fisioterapia', 'CSA-FAFI', 3, 'teórica', 144),
        ('Farmacología y Anestesia', 'CSA-FRAN', 3, 'teórica', 144),
        ('Farmacología y Toxicología', 'CSA-FTOX', 3, 'teórica', 144),
        ('Farmacología y Toxicología Básica', 'CSA-FTBA', 3, 'teórica', 144),
        ('Filosofía del Derecho', 'DER-FIDE', 3, 'teórica', 144),
        ('Finanzas Corporativas', 'CEA-FICO', 3, 'teórica', 144),
        ('Finanzas Internacionales', 'CEA-FIIN', 3, 'teórica', 144),
        ('Finanzas Públicas', 'DER-FIPU', 3, 'teórica', 144),
        ('Fisiología', 'CSA-FISIO', 3, 'teórica', 144),
        ('Fisiología del Ejercicio', 'CSA-FIEJ', 3, 'teórica', 144),
        ('Fisiopatología Animal', 'CSA-FPAN', 3, 'teórica', 144),
        ('Fisiopatología Humana', 'CSA-FPHY', 5, 'práctica', 240),
        ('Fisiopatología Vegetal', 'CSA-FPVE', 3, 'teórica', 144),
        ('Formulación y Evaluación de Proyectos', 'ING-FEPR', 3, 'teórica', 144),
        ('Formulación y Gestión de Proyectos', 'CEA-FGPR', 3, 'teórica', 144),
        ('Fundamentos de Administración', 'CEA-FDAD', 3, 'teórica', 144),
        ('Fundamentos de Bases de Datos', 'ING-FBDA', 3, 'teórica', 144),
        ('Fundamentos de Economía', 'CEA-FDEC', 3, 'teórica', 144),
        ('Fundamentos de Matemáticas', 'CEA-FDMA', 3, 'teórica', 144),
        ('Fundamentos de Mercadeo', 'CEA-FDME', 3, 'teórica', 144),
        ('Fundamentos de Negocios Internacionales', 'CEA-FDNI', 3, 'teórica', 144),
        ('Fundamentos de Programación', 'ING-FDPR', 3, 'teórica', 144),
        ('Fundamentos de Psicología', 'CSA-FDPS', 3, 'teórica', 144),
        ('Fundamentos en Análisis y Redacción de Texto', 'CSA-FART', 3, 'teórica', 144),
        ('Fundamentos y Normatividad Tributaria', 'CEA-FDNT', 3, 'teórica', 144),
        ('Física', 'CSA-FIS', 3, 'teórica', 144),
        ('Física Mecánica', 'ING-FIME', 3, 'teórica', 144),
        ('Genética', 'CSA-GEN', 3, 'teórica', 144),
        ('Genética Clínica', 'CSA-GECL', 3, 'teórica', 144),
        ('Geopolítica', 'CEA-GEOP', 3, 'teórica', 144),
        ('Gerencia Estratégica', 'ING-GERE', 3, 'teórica', 144),
        ('Gerencia Estratégica Organizacional', 'CEA-GEOR', 3, 'teórica', 144),
        ('Gerencia de Comercio Exterior', 'CEA-GCEX', 3, 'teórica', 144),
        ('Gestión de Exportaciones', 'CEA-GEXP', 3, 'teórica', 144),
        ('Gestión de Importaciones', 'CEA-GIMP', 3, 'teórica', 144),
        ('Gestión de Proyectos de Ingeniería', 'ING-GPIN', 3, 'teórica', 144),
        ('Gestión de la Planeación y Organización', 'CEA-GPOR', 3, 'teórica', 144),
        ('Gestión del Talento Humano', 'CEA-GTHA', 3, 'teórica', 144),
        ('Gestión del Transporte Internacional', 'CEA-GTIN', 3, 'teórica', 144),
        ('Gineco-Obstetricia', 'CSA-GIOB', 3, 'teórica', 144),
        ('Gineco-Obstetricia INT.', 'CSA-GIOB2', 3, 'teórica', 144),
        ('Globalización', 'CEA-GLOB', 3, 'teórica', 144),
        ('Habilidades Comunicativas', 'DER-HACO', 3, 'teórica', 144),
        ('Hematología', 'CSA-HEMA', 3, 'teórica', 144),
        ('Hematología Clínica', 'CSA-HECL', 3, 'teórica', 144),
        ('Hermenéutica Jurídica', 'DER-HEJR', 3, 'teórica', 144),
        ('Historia de la Ciencia', 'CSA-HCIE', 3, 'teórica', 144),
        ('Historia de la Filosofía', 'DER-HIFL', 3, 'teórica', 144),
        ('Impuesto Sobre la Renta', 'CEA-IMRE', 3, 'teórica', 144),
        ('Impuesto a las Ventas y Retención', 'CEA-IVYR', 3, 'teórica', 144),
        ('Impuestos Territoriales y Proc. Tributario', 'CEA-ITPT', 3, 'teórica', 144),
        ('Electiva: BASIC BUSINESS ENGLISH', 'CEA-BBEN', 2, 'teórica', 96),
        ('Electiva: INTERMEDIATE ACCOUNTING ENGLISH', 'CEA-IAEN', 2, 'teórica', 96),
        ('ELECTIVA: ADVANCED BUSINESS ENGLISH', 'CEA-ABEN', 2, 'teórica', 96),
        ('Ingeniería Aplicada', 'ING-INAP', 3, 'teórica', 144),
        ('Ingeniería de Software I', 'ING-ISW1', 3, 'teórica', 144),
        ('Ingeniería de Software II', 'ING-ISW2', 3, 'teórica', 144),
        ('Ingeniería de Software III', 'ING-ISW3', 3, 'teórica', 144),
        ('Inmunohematología y Banco de Sangre', 'CSA-IMBS', 3, 'teórica', 144),
        ('Inmunología', 'CSA-INMU', 3, 'teórica', 144),
        ('Inmunología Básica', 'CSA-IMBA', 3, 'teórica', 144),
        ('Inmunología Clínica', 'CSA-IMCL', 3, 'teórica', 144),
        ('Innovación y Tecnología', 'CSA-INTE', 3, 'teórica', 144),
        ('Inteligencia Artificial', 'ING-INAR', 3, 'teórica', 144),
        ('International Agreement', 'CEA-INTA', 3, 'teórica', 144),
        ('International Marketing', 'CEA-INTM', 3, 'teórica', 144),
        ('Intervención en Fisioterapia I', 'CSA-IFI1', 3, 'teórica', 144),
        ('Intervención en Fisioterapia II', 'CSA-IFI2', 3, 'teórica', 144),
        ('Intervención en Fisioterapia III', 'CSA-IFI3', 3, 'teórica', 144),
        ('Introducción a la Fisioterapia', 'CSA-INFI', 3, 'teórica', 144),
        ('Introducción a la Ingeniería', 'ING-INGE', 3, 'teórica', 144),
        ('Introducción a la Instrumentación', 'CSA-ININ', 3, 'teórica', 144),
        ('Introducción a las Tecnologías Ómicas', 'CSA-INTO', 3, 'teórica', 144),
        ('Introducción al Derecho', 'DER-INDE', 3, 'teórica', 144),
        ('Investigación Clínica Epidemiológica', 'CSA-ICEP', 3, 'teórica', 144),
        ('Investigación I', 'DER-INI1', 3, 'teórica', 144),
        ('Investigación II', 'DER-INI2', 3, 'teórica', 144),
        ('Investigación III', 'DER-INI3', 3, 'teórica', 144),
        ('Investigación IV', 'DER-INI4', 3, 'teórica', 144),
        ('Investigación de Mercados', 'CEA-INME', 3, 'teórica', 144),
        ('Investigación de Operaciones', 'CEA-INOP', 3, 'teórica', 144),
        ('Jurisprudencia Constitucional', 'DER-JUCO', 3, 'teórica', 144),
        ('Laboral Administrativo', 'DER-LAAD', 3, 'teórica', 144),
        ('Laboral Colectivo', 'DER-LACO', 3, 'teórica', 144),
        ('Laboral Individual y Prestacional', 'DER-LAIP', 3, 'teórica', 144),
        ('Legislación Aduanera', 'CEA-LEAD', 3, 'teórica', 144),
        ('Logística y Distribución Física Internacional', 'CEA-LDFI', 3, 'teórica', 144),
        ('Lógica Jurídica', 'DER-LGJU', 3, 'teórica', 144),
        ('Lógica Matemática', 'CSA-LGMA', 3, 'teórica', 144),
        ('Lógica Matemáticas', 'ING-LGMA2', 3, 'teórica', 144),
        ('Lógica y Algoritmos', 'ING-LGAL', 3, 'teórica', 144),
        ('Matemáticas', 'CSA-MAT', 3, 'teórica', 144),
        ('Matemáticas Discretas', 'ING-MADE', 3, 'teórica', 144),
        ('Matemáticas Financieras', 'CEA-MAFI', 3, 'teórica', 144),
        ('Medicina Interna', 'CSA-MEIN', 3, 'teórica', 144),
        ('Medicina Interna INT.', 'CSA-MEIN2', 3, 'teórica', 144),
        ('Medicina Legal', 'CSA-MELE', 3, 'teórica', 144),
        ('Mercado de Capitales', 'CEA-MECA', 3, 'teórica', 144),
        ('Metodología de la Investigación', 'CSA-METI', 3, 'teórica', 144),
        ('Micología Clínica', 'CSA-MICL', 3, 'teórica', 144),
        ('Microbiología', 'CSA-MICR', 3, 'teórica', 144),
        ('Microbiología Ambiental', 'CSA-MIAM', 3, 'teórica', 144),
        ('Microbiología General', 'CSA-MIGE', 3, 'teórica', 144),
        ('Microbiología Industrial', 'CSA-MIIN', 3, 'teórica', 144),
        ('Microbiología Predictiva', 'CSA-MIPR', 3, 'teórica', 144),
        ('Microbiología de Alimentos y Medicamentos', 'CSA-MIAM2', 3, 'teórica', 144),
        ('Microbiología de Suelos', 'CSA-MISU', 3, 'teórica', 144),
        ('Modalidades Físicas', 'CSA-MOFI', 3, 'teórica', 144),
        ('Modelos de Investigación', 'CEA-MOIN', 3, 'teórica', 144),
        ('Morfofisiología I', 'CSA-MFI1', 3, 'teórica', 144),
        ('Morfofisiología II', 'CSA-MFI2', 3, 'teórica', 144),
        ('Morfología I', 'CSA-MOR1', 3, 'teórica', 144),
        ('Morfología II', 'CSA-MOR2', 3, 'teórica', 144),
        ('Neurociencia del Movimiento', 'CSA-NEMO', 3, 'teórica', 144),
        ('Obligaciones', 'DER-OBLI', 3, 'teórica', 144),
        ('Ocupación y Movimiento Corporal', 'CSA-OCMC', 3, 'teórica', 144),
        ('Optativa I', 'CEA-OPT1', 2, 'teórica', 96),
        ('Optativa II - Innovación y Transformación Digital en Empresas Globales', 'CEA-OPT2', 2, 'teórica', 96),
        ('Optativa II. Administración Estratégica', 'CEA-OPT2A', 2, 'teórica', 96),
        ('Optativa III', 'CEA-OPT3', 2, 'teórica', 96),
        ('Optativa III (Gestión de Procesos)', 'CEA-OPT3B', 2, 'teórica', 96),
        ('Optativa IV Gestión y Responsabilidad Fiscal', 'DER-OPT4', 2, 'teórica', 96),
        ('Optativa V', 'DER-OPT5', 2, 'teórica', 96),
        ('Optativa de Énfasis I', 'CEA-OEF1', 2, 'teórica', 96),
        ('Optativa de Énfasis III', 'CEA-OEF3', 2, 'teórica', 96),
        ('Optativa III. DESARROLLO DEL FACTOR HUMANO', 'CEA-OPT3A', 2, 'teórica', 96),
        ('POSGRADOS', 'POSGRADOS', 2, 'teórica', 96),
        ('Parasitología Clínica', 'CSA-PACL', 3, 'teórica', 144),
        ('Patología', 'CSA-PATO', 3, 'teórica', 144),
        ('Pediatría', 'CSA-PEDI', 5, 'práctica', 240),
        ('Pensamiento Sistémico', 'ING-PESI', 5, 'práctica', 240),
        ('Prescripción del Ejercicio', 'CSA-PREJ', 3, 'teórica', 144),
        ('Presupuestos Empresariales', 'CEA-PREM', 3, 'teórica', 144),
        ('Principios de Derecho y Constitución', 'CEA-PDCO', 3, 'teórica', 144),
        ('Probabilidad y Estadística Descriptiva', 'ING-PRED', 3, 'teórica', 144),
        ('Probatorio', 'DER-PROB', 3, 'teórica', 144),
        ('Procesal Administrativo I', 'DER-PAD1', 3, 'teórica', 144),
        ('Procesal Administrativo II', 'DER-PAD2', 3, 'teórica', 144),
        ('Procesal Civil Especial y de Familia', 'DER-PCEF', 3, 'teórica', 144),
        ('Procesal Civil General', 'DER-PCGE', 3, 'teórica', 144),
        ('Procesal Laboral', 'DER-PLAB', 3, 'teórica', 144),
        ('Procesal Penal I', 'DER-PPE1', 3, 'teórica', 144),
        ('Procesal Penal II', 'DER-PPE2', 3, 'teórica', 144),
        ('Procesos Asépticos I', 'CSA-PAS1', 3, 'teórica', 144),
        ('Procesos Asépticos II', 'CSA-PAS2', 3, 'teórica', 144),
        ('Procesos Industriales', 'CSA-PRIN2', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Cardiovascular', 'CSA-PQCV', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Cirugía General y Pediatría', 'CSA-PQGP', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Cirugía Maxilofacial', 'CSA-PQCM', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Cirugía Plástica', 'CSA-PQCP', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Gineco-Obstetricia', 'CSA-PQGO', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Neurocirugía', 'CSA-PQNE', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Oftalmología', 'CSA-PQOF', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Ortopedia', 'CSA-PQOR', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Otorrinolaringología', 'CSA-PQOT', 3, 'teórica', 144),
        ('Procesos Quirúrgicos en Urología', 'CSA-PQUR', 3, 'teórica', 144),
        ('Programación I', 'ING-PRG1', 3, 'teórica', 144),
        ('Programación II', 'ING-PRG2', 3, 'teórica', 144),
        ('Programación Lineal', 'ING-PRLI', 3, 'teórica', 144),
        ('Programación Móvil', 'ING-PRMO', 3, 'teórica', 144),
        ('Programación Web', 'ING-PRWE', 3, 'teórica', 144),
        ('Proyección a la Comunidad', 'CSA-PRCO', 3, 'teórica', 144),
        ('Proyecto de Investigación', 'CSA-PRIN', 3, 'teórica', 144),
        ('Proyecto de Investigación (Bacteriología)', 'CSA-PRIB', 3, 'teórica', 144),
        ('Proyecto de Investigación II', 'CSA-PRI2', 3, 'teórica', 144),
        ('Proyecto de Investigación III', 'CSA-PRI3', 3, 'teórica', 144),
        ('Práctica Clínica', 'CSA-PRCL', 5, 'práctica', 240),
        ('Práctica Clínica Básica', 'CSA-PRCB', 5, 'práctica', 240),
        ('Práctica Empresarial', 'ING-PREM2', 5, 'práctica', 240),
        ('Práctica Hospitalaria I', 'CSA-PRH1', 5, 'práctica', 240),
        ('Práctica Hospitalaria II', 'CSA-PRH2', 5, 'práctica', 240),
        ('Práctica Hospitalaria III', 'CSA-PRH3', 5, 'práctica', 240),
        ('Práctica Hospitalaria IV', 'CSA-PRH4', 5, 'práctica', 240),
        ('Práctica de Administración', 'CSA-PRAD', 5, 'práctica', 240),
        ('Prácticas Formativas', 'CSA-PRFO', 5, 'práctica', 240),
        ('Prácticas Optativas', 'CSA-PROP', 5, 'práctica', 240),
        ('Prácticas Profesionales', 'CSA-PRPR', 5, 'práctica', 240),
        ('Psicología Evolutiva', 'CSA-PSEV', 3, 'teórica', 144),
        ('Psicología de la Salud', 'CSA-PSSA', 3, 'teórica', 144),
        ('Psicología del Desarrollo', 'CSA-PSDE', 3, 'teórica', 144),
        ('Psicopatología', 'CSA-PSCP', 3, 'teórica', 144),
        ('Psiquiatría', 'CSA-PSIQ', 3, 'teórica', 144),
        ('Química', 'CSA-QUIM', 3, 'teórica', 144),
        ('Química Clínica', 'CSA-QUCL', 3, 'teórica', 144),
        ('Química Especial', 'CSA-QUES', 3, 'teórica', 144),
        ('Redes de Computadores', 'ING-RECO', 3, 'teórica', 144),
        ('Responsabilidad Civil', 'DER-RECI', 3, 'teórica', 144),
        ('Revisoría Fiscal', 'CEA-REFI', 3, 'teórica', 144),
        ('Régimen Cambiario y Aduanero', 'CEA-RCYA', 3, 'teórica', 144),
        ('Salud Familiar I', 'CSA-SAF1', 3, 'teórica', 144),
        ('Salud Familiar II', 'CSA-SAF2', 3, 'teórica', 144),
        ('Salud Pública', 'CSA-SAPU', 3, 'teórica', 144),
        ('Salud Pública (Práctica Comunitaria)', 'CSA-SAPC', 3, 'teórica', 144),
        ('Salud Pública I', 'CSA-SAP1', 3, 'teórica', 144),
        ('Salud Pública II', 'CSA-SAP2', 3, 'teórica', 144),
        ('Salud y Ambiente', 'CSA-SAMY', 3, 'teórica', 144),
        ('Salud y Comunidad', 'CSA-SAYU', 3, 'teórica', 144),
        ('Salud y Seguridad en el Trabajo', 'CSA-SSET', 3, 'teórica', 144),
        ('Seguridad Social', 'DER-SESO', 3, 'teórica', 144),
        ('Seguridad de la Información', 'ING-SEIN', 3, 'teórica', 144),
        ('Seguridad y Salud en el Trabajo', 'CSA-SSTR', 3, 'teórica', 144),
        ('Seminario de Negociación y Concertación', 'CEA-SENE', 3, 'teórica', 144),
        ('Semiología', 'CSA-SEMI', 3, 'teórica', 144),
        ('Simulación Gerencial', 'CEA-SIGE', 3, 'teórica', 144),
        ('Sistemas Integrados de Gestión', 'ING-SIGE2', 3, 'teórica', 144),
        ('Sistemas Operativos', 'ING-SIOP', 3, 'teórica', 144),
        ('Sistemas de Bases de Datos', 'ING-SBDA', 3, 'teórica', 144),
        ('Sistemas de Calidad', 'CSA-SICA', 3, 'teórica', 144),
        ('Sistemas de Costeo', 'CEA-SICO', 3, 'teórica', 144),
        ('Sociedad, Sector Salud y Comunidad', 'CSA-SSSC', 3, 'teórica', 144),
        ('Socioantropología', 'CSA-SCAN', 3, 'teórica', 144),
        ('Sociología General y Jurídica', 'DER-SGJU', 3, 'teórica', 144),
        ('Solución Alternativa de Conflictos', 'DER-SACO', 3, 'teórica', 144),
        ('Sucesiones', 'DER-SUCE', 3, 'teórica', 144),
        ('Teoría Económica', 'DER-TEEC', 3, 'teórica', 144),
        ('Teoría General del Proceso', 'DER-TGPR', 3, 'teórica', 144),
        ('Teoría de la Constitución', 'DER-TECO2', 3, 'teórica', 144),
        ('Teoría del Delito', 'DER-TEDE', 3, 'teórica', 144),
        ('Teoría del Estado', 'DER-TEES', 3, 'teórica', 144),
        ('Teorías Contables', 'CEA-TECO', 3, 'teórica', 144),
        ('Toxicología', 'CSA-TOXC', 3, 'teórica', 144),
        ('Trabajo de Grado', 'CSA-TRGR', 3, 'teórica', 144),
        ('Trabajo de Investigación', 'CSA-TRIN', 3, 'teórica', 144),
        ('Tutela Penal de los Bienes Jurídicos I', 'DER-TPB1', 3, 'teórica', 144),
        ('Tutela Penal de los Bienes Jurídicos II', 'DER-TPB2', 3, 'teórica', 144),
        ('Títulos Valores', 'DER-TVAL', 3, 'teórica', 144),
        ('Urgencia Adulto', 'CSA-URAD', 3, 'teórica', 144),
        ('Virología Clínica', 'CSA-VICL', 3, 'teórica', 144),
        ('Álgebra Lineal', 'ING-ALGE', 3, 'teórica', 144),
        ('Ética General y Deontología IQ', 'CSA-EGDI', 3, 'teórica', 144),
        ('Ética I', 'DER-ETI1', 3, 'teórica', 144),
        ('Ética II', 'DER-ETI2', 3, 'teórica', 144),
        ('Ética Médica', 'CSA-ETME', 3, 'teórica', 144),
        ('Ética Profesional', 'ING-ETPR', 3, 'teórica', 144),
        ('Ética Profesional y Responsabilidad Social', 'CEA-EPRS', 3, 'teórica', 144),
        ('Ética y Bioética', 'CSA-ETBI', 3, 'teórica', 144),
        
        # Nuevas asignaturas de Ingeniería Industrial
        ('Bioestadística y Demografía', 'CSA-BIDE', 3, 'teórica', 144),
        ('Ciencia de los Materiales en la Industria', 'ING-CMDI', 3, 'teórica', 144),
        ('Contabilidad y Presupuesto', 'ING-COPR', 3, 'teórica', 144),
        ('Control Estadístico de la Calidad', 'ING-CECQ', 3, 'teórica', 144),
        ('Costos de Operación', 'ING-CSOP', 3, 'teórica', 144),
        ('Diseño de Instalaciones Industriales y de Servicios', 'ING-DIIS', 3, 'teórica', 144),
        ('Diseño de Productos y Servicios', 'ING-DPSE', 3, 'teórica', 144),
        ('Electricidad Magnetismo y Laboratorio', 'ING-EMYL', 3, 'teórica', 144),
        ('Epidemiología (Fisioterapia)', 'CSA-EPFI', 3, 'teórica', 144),
        ('Expresión Gráfica para Ingeniería', 'ING-EGPI', 3, 'teórica', 144),
        ('Finanzas', 'ING-FINA', 3, 'teórica', 144),
        ('Física Mecánica y Lab', 'ING-FMLA', 3, 'teórica', 144),
        ('Gestión Organizacional', 'ING-GEOR2', 3, 'teórica', 144),
        ('Gestión de la Tecnología', 'ING-GETE', 3, 'teórica', 144),
        ('Historia de la Medicina', 'CSA-HMED', 3, 'teórica', 144),
        ('Ingeniería Económica', 'ING-INEC', 3, 'teórica', 144),
        ('Ingeniería de Métodos', 'ING-INME', 3, 'teórica', 144),
        ('Investigación Operativa I', 'ING-IOPI', 3, 'teórica', 144),
        ('Investigación Operativa II', 'ING-IOPII', 3, 'teórica', 144),
        ('Lenguaje de Programación', 'ING-LGPR', 3, 'teórica', 144),
        ('Logística y Cadena de Suministros', 'ING-LCSU', 3, 'teórica', 144),
        ('Mercadeo', 'ING-MERC', 3, 'teórica', 144),
        ('Modelos Matemáticos Estocásticos', 'ING-MMES', 3, 'teórica', 144),
        ('Optativa de Énfasis I', 'CEA-OEF1', 3, 'teórica', 144),
        ('Optativa de Énfasis III', 'CEA-OEF3', 3, 'teórica', 144),
        ('Planeación y Control de la Producción y Operaciones', 'ING-PCPO', 3, 'teórica', 144),
        ('Química General y Laboratorio', 'ING-QGLA', 3, 'teórica', 144),
        ('Seguridad y Salud en el Trabajo (IND)', 'ING-SSTI', 3, 'teórica', 144),
        ('Seguridad y Salud en el Trabajo (MED)', 'CSA-SSTM', 3, 'teórica', 144),
        ('Simulación de Procesos', 'ING-SIPR', 3, 'teórica', 144),
        ('Termodinámica', 'ING-TERM', 3, 'teórica', 144),
        ('Ética (Ingeniería)', 'ING-ETIC', 3, 'teórica', 144),
        
        # Asignaturas de Alianza Canadiense (Modalidades)
        ('Modalidad Intensiva', 'ALI-INTE', 3, 'teórica', 144),
        ('Modalidad Semestral', 'ALI-SEME', 3, 'teórica', 144),
        ('Modalidad Sabatina', 'ALI-SABA', 3, 'teórica', 144),
        ('Modalidad Semi-Intensiva', 'ALI-SEMI', 3, 'teórica', 144),
    ]
