"""
Seeder de asignaturas de todos los programas.
"""

from asignaturas.models import Asignatura


def create_asignaturas(stdout, style):
    """Crear todas las asignaturas de todos los programas"""
    stdout.write('  → Creando asignaturas...')
    stdout.write('     Este proceso puede tomar unos segundos...')
    
    asignaturas_data = _get_all_asignaturas()
    
    created_count = 0
    updated_count = 0
    
    for nombre, codigo, creditos, tipo_str, horas in asignaturas_data:
        # Mapear tipo string a choice del modelo
        tipo_map = {
            'Teórica': 'teórica',
            'Práctica': 'práctica',
            'Teórica/Práctica': 'mixta',
            'Mixta': 'mixta'
        }
        tipo = tipo_map.get(tipo_str, 'teórica')
        
        asignatura, created = Asignatura.objects.get_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'creditos': creditos,
                'tipo': tipo,
                'horas': horas
            }
        )
        
        if created:
            created_count += 1
        elif (asignatura.nombre != nombre or asignatura.creditos != creditos or 
              asignatura.tipo != tipo or asignatura.horas != horas):
            # Actualizar si hay cambios
            asignatura.nombre = nombre
            asignatura.creditos = creditos
            asignatura.tipo = tipo
            asignatura.horas = horas
            asignatura.save()
            updated_count += 1
    
    total = len(asignaturas_data)
    stdout.write(style.SUCCESS(f'    ✓ Asignaturas procesadas: {created_count} nuevas, {updated_count} actualizadas, {total} totales'))


def _get_all_asignaturas():
    """Retorna la lista completa de asignaturas de todos los programas"""
    # Formato: (nombre, código, créditos, tipo, horas)
    return [
        # === NEGOCIOS INTERNACIONALES (NI) ===
        ('Fundamentos de Matemáticas', 'NI-FM', 4, 'Teórica', 4),
        ('Principios de Derecho y Constitución', 'NI-PDC', 2, 'Teórica', 2),
        ('Expresión Verbal y Escrita', 'NI-EVE', 2, 'Teórica', 2),
        ('Emprendimiento e Innovación', 'NI-EI', 2, 'Teórica/Práctica', 2),
        ('Fundamentos de Economía', 'NI-FE', 2, 'Teórica', 2),
        ('Fundamentos de Administración', 'NI-FA', 3, 'Teórica', 3),
        ('Fundamentos de Negocios Internacionales', 'NI-FNI', 3, 'Teórica', 3),
        ('Cálculo', 'NI-CAL', 4, 'Teórica', 4),
        ('Epistemología y Metodología de la Investigación', 'NI-EMI', 2, 'Teórica', 2),
        ('Contabilidad Financiera', 'NI-CF', 3, 'Teórica/Práctica', 3),
        ('Economía de Empresa', 'NI-EE', 2, 'Teórica', 2),
        ('Derecho Comercial', 'NI-DC', 2, 'Teórica', 2),
        ('Gestión de la Planeación y Organización', 'NI-GPO', 3, 'Teórica/Práctica', 3),
        ('Estadística Descriptiva', 'NI-ED', 3, 'Teórica', 3),
        ('Matemáticas Financieras', 'NI-MF', 3, 'Teórica', 3),
        ('Derecho Laboral y de Seguridad Social', 'NI-DLSS', 2, 'Teórica', 2),
        ('Sistemas de Costeo', 'NI-SC', 3, 'Teórica/Práctica', 3),
        ('Coyuntura Económica Nacional', 'NI-CEN', 2, 'Teórica', 2),
        ('Presupuestos Empresariales', 'NI-PE', 3, 'Teórica/Práctica', 3),
        ('Dirección y Liderazgo', 'NI-DL', 2, 'Teórica/Práctica', 2),
        ('Estadística Inferencial', 'NI-EI2', 3, 'Teórica', 3),
        ('Administración Financiera', 'NI-AF', 3, 'Teórica/Práctica', 3),
        ('Fundamentos de Mercadeo', 'NI-FMERC', 3, 'Teórica/Práctica', 3),
        ('Geopolítica', 'NI-GEO', 2, 'Teórica', 2),
        ('Gestión del Talento Humano', 'NI-GTH', 3, 'Teórica/Práctica', 3),
        ('Legislación Aduanera', 'NI-LA', 2, 'Teórica', 2),
        ('Coyuntura Económica Internacional', 'NI-CEI', 2, 'Teórica', 2),
        ('Modelos de Investigación', 'NI-MI', 2, 'Teórica', 2),
        ('Investigación de Operaciones', 'NI-IO', 3, 'Teórica/Práctica', 3),
        ('Desarrollo e Innovación de las Organizaciones', 'NI-DIO', 3, 'Teórica/Práctica', 3),
        ('Comercio y Negocios Globales', 'NI-CNG', 2, 'Teórica', 2),
        ('Finanzas Corporativas', 'NI-FC', 3, 'Teórica/Práctica', 3),
        ('Derecho Comercial Internacional', 'NI-DCI', 2, 'Teórica', 2),
        ('Logística y Distribución Física Internacional', 'NI-LDFI', 2, 'Teórica/Práctica', 2),
        ('Formulación y Gestión de Proyectos', 'NI-FGP', 3, 'Teórica/Práctica', 3),
        ('Electiva I', 'NI-ELEC1', 2, 'Teórica', 2),
        ('Investigación de Mercados', 'NI-IM', 3, 'Teórica/Práctica', 3),
        ('Finanzas Internacionales', 'NI-FI', 3, 'Teórica/Práctica', 3),
        ('Gestión de Importaciones', 'NI-GI', 2, 'Teórica/Práctica', 2),
        ('Gestión del Transporte Internacional', 'NI-GTI', 2, 'Teórica/Práctica', 2),
        ('Optativa de Énfasis I', 'NI-OE1', 4, 'Teórica/Práctica', 4),
        ('Electiva II', 'NI-ELEC2', 2, 'Teórica', 2),
        ('Seminario de Negociación y Concertación', 'NI-SNC', 2, 'Teórica/Práctica', 2),
        ('International Marketing', 'NI-IMKT', 2, 'Teórica/Práctica', 2),
        ('Proyecto de Investigación', 'NI-PI', 2, 'Teórica', 2),
        ('International Agreement', 'NI-IA', 3, 'Teórica', 3),
        ('Gerencia de Comercio Exterior', 'NI-GCE', 3, 'Teórica/Práctica', 3),
        ('Gestión de Exportaciones', 'NI-GEX', 2, 'Teórica/Práctica', 2),
        ('Optativa de Énfasis II', 'NI-OE2', 3, 'Teórica/Práctica', 3),
        ('Electiva III', 'NI-ELEC3', 2, 'Teórica', 2),
        ('Simulación Gerencial', 'NI-SG', 2, 'Teórica/Práctica', 2),
        ('Régimen Cambiario y Aduanero', 'NI-RCA', 2, 'Teórica', 2),
        ('Mercado de Capitales', 'NI-MC', 2, 'Teórica', 2),
        ('Ética Profesional y Responsabilidad Social', 'NI-EPRS', 2, 'Teórica', 2),
        ('Globalización', 'NI-GLOB', 3, 'Teórica', 3),
        ('Optativa de Énfasis III', 'NI-OE3', 4, 'Teórica/Práctica', 4),
        
        # === CONTADURÍA PÚBLICA (CP) ===
        ('Fundamentos de Matemáticas', 'CP-FM', 4, 'Teórica', 4),
        ('Fundamentos de Economía', 'CP-FE', 4, 'Teórica', 4),
        ('Principios de Derecho y Constitución', 'CP-PDC', 2, 'Teórica', 2),
        ('Expresión Verbal y Escrita', 'CP-EVE', 2, 'Teórica', 2),
        ('Cátedra Unilibrista', 'CP-CU', 2, 'Teórica', 2),
        ('Electiva I', 'CP-ELEC1', 1, 'Teórica', 1),
        ('Fundamentos de Administración', 'CP-FA', 2, 'Teórica', 2),
        ('Cálculo I', 'CP-CAL1', 4, 'Teórica', 4),
        ('Economía de Empresa', 'CP-EE', 4, 'Teórica', 4),
        ('Epistemología y Metodología de la Investigación', 'CP-EMI', 2, 'Teórica', 2),
        ('Derecho Comercial', 'CP-DC', 3, 'Teórica', 3),
        ('Contabilidad Financiera', 'CP-CF', 2, 'Teórica/Práctica', 2),
        ('Electiva II', 'CP-ELEC2', 2, 'Teórica', 2),
        ('Ciclo de Egresos y Administración de Inventarios', 'CP-CEAI', 4, 'Teórica/Práctica', 4),
        ('Teorías Contables', 'CP-TC', 2, 'Teórica', 2),
        ('Matemáticas Financieras', 'CP-MF', 3, 'Teórica', 3),
        ('Estadística Descriptiva', 'CP-ED', 3, 'Teórica', 3),
        ('Coyuntura Económica Nacional', 'CP-CEN', 2, 'Teórica', 2),
        ('Emprendimiento e Innovación', 'CP-EI', 2, 'Teórica/Práctica', 2),
        ('Derecho Laboral y de Seguridad Social', 'CP-DLSS', 2, 'Teórica', 2),
        ('Ciclo de Inversiones y Financiación', 'CP-CIF', 4, 'Teórica/Práctica', 4),
        ('Sistemas de Costeo', 'CP-SC', 4, 'Teórica/Práctica', 4),
        ('Contabilidad Ambiental', 'CP-CA', 2, 'Teórica', 2),
        ('Estadística Inferencial', 'CP-EI2', 3, 'Teórica', 3),
        ('Gerencia Estratégica Organizacional', 'CP-GEO', 2, 'Teórica', 2),
        ('Fundamentos de Mercadeo', 'CP-FMERC', 2, 'Teórica/Práctica', 2),
        ('Modelos de Investigación', 'CP-MI', 2, 'Teórica', 2),
        ('Ciclo de Estados Financieros', 'CP-CEF', 4, 'Teórica/Práctica', 4),
        ('Costos Gerenciales', 'CP-CG', 4, 'Teórica/Práctica', 4),
        ('Fundamentos y Normatividad Tributaria', 'CP-FNT', 2, 'Teórica', 2),
        ('Aseguramiento y Fundamentos de Control', 'CP-AFC', 3, 'Teórica', 3),
        ('Investigación de Operaciones', 'CP-IO', 2, 'Teórica/Práctica', 2),
        ('Electiva III', 'CP-ELEC3', 1, 'Teórica', 1),
        ('Electiva IV', 'CP-ELEC4', 2, 'Teórica', 2),
        ('Auditoría Aplicada', 'CP-AA', 4, 'Teórica/Práctica', 4),
        ('Impuesto sobre la Renta y Complementarios', 'CP-IRC', 4, 'Teórica', 4),
        ('Presupuestos Empresariales', 'CP-PE', 3, 'Teórica/Práctica', 3),
        ('Administración Financiera', 'CP-AF', 3, 'Teórica/Práctica', 3),
        ('Optativa I', 'CP-OPT1', 3, 'Teórica/Práctica', 3),
        ('Comercio y Negocios Globales', 'CP-CNG', 2, 'Teórica', 2),
        ('Revisoría Fiscal', 'CP-RF', 4, 'Teórica/Práctica', 4),
        ('Contabilidad y Finanzas Públicas', 'CP-CFP', 3, 'Teórica', 3),
        ('Finanzas Corporativas', 'CP-FC', 3, 'Teórica/Práctica', 3),
        ('Formulación y Gestión de Proyectos', 'CP-FGP', 3, 'Teórica/Práctica', 3),
        ('Impuesto a las Ventas y Retención en la Fuente', 'CP-IVRF', 3, 'Teórica', 3),
        ('Optativa II', 'CP-OPT2', 2, 'Teórica/Práctica', 2),
        ('Impuestos Territoriales y Procedimiento Tributario', 'CP-ITPT', 3, 'Teórica', 3),
        ('Auditoría de Sistemas', 'CP-AS', 3, 'Teórica/Práctica', 3),
        ('Ética Profesional', 'CP-EP', 3, 'Teórica', 3),
        ('Optativa III', 'CP-OPT3', 3, 'Teórica/Práctica', 3),
        ('Simulación Gerencial', 'CP-SG', 3, 'Teórica/Práctica', 3),
        ('Electiva V', 'CP-ELEC5', 4, 'Teórica', 4),
        ('Ciclo Básica Contable', 'CP-CBC', 3, 'Teórica', 3),
        
        # === INSTRUMENTACIÓN QUIRÚRGICA (IQ) ===
        ('Biología', 'IQ-BIO', 2, 'Teórica', 2),
        ('Morfofisiología I', 'IQ-MF1', 3, 'Teórica/Práctica', 3),
        ('Biofísica', 'IQ-BF', 2, 'Teórica', 2),
        ('Química', 'IQ-QUI', 2, 'Teórica', 2),
        ('Introducción a la Instrumentación', 'IQ-IIQ', 2, 'Teórica/Práctica', 2),
        ('Competencias Comunicativas I', 'IQ-CC1', 2, 'Teórica', 2),
        ('Sociedad, Sector Salud y Comunidad', 'IQ-SSSC', 2, 'Teórica', 2),
        ('Cátedra Unilibrista', 'IQ-CU', 1, 'Teórica', 1),
        ('Bioquímica', 'IQ-BQ', 2, 'Teórica', 2),
        ('Morfofisiología II', 'IQ-MF2', 3, 'Teórica/Práctica', 3),
        ('Microbiología', 'IQ-MIC', 3, 'Teórica/Práctica', 3),
        ('Fundamentos de Psicología', 'IQ-FPS', 2, 'Teórica', 2),
        ('Competencias Comunicativas II', 'IQ-CC2', 2, 'Teórica', 2),
        ('Bioestadística e Informática', 'IQ-BEI', 2, 'Teórica/Práctica', 2),
        ('Ética General y Deontología de la Instrumentación Quirúrgica', 'IQ-EGDIQ', 3, 'Teórica', 3),
        ('Patología', 'IQ-PAT', 3, 'Teórica', 3),
        ('Control de Infecciones y Promoción de la Salud', 'IQ-CIPS', 2, 'Teórica/Práctica', 2),
        ('Procesos Asépticos I', 'IQ-PA1', 3, 'Práctica', 3),
        ('Cuidados Básicas en Salud', 'IQ-CBS', 3, 'Teórica/Práctica', 3),
        ('Investigación Clínica Epidemiológica', 'IQ-ICE', 2, 'Teórica', 2),
        ('Farmacología y Anestesia', 'IQ-FA', 3, 'Teórica/Práctica', 3),
        ('Socioantropología', 'IQ-SA', 2, 'Teórica', 2),
        ('Electiva Complementaria I', 'IQ-EC1', 1, 'Teórica', 1),
        ('Procesos Quirúrgicos en Cirugía General y Pediatría', 'IQ-PQCGP', 4, 'Práctica', 4),
        ('Procesos Quirúrgicos en Urología', 'IQ-PQU', 2, 'Práctica', 2),
        ('Constitución Nacional', 'IQ-CN', 2, 'Teórica', 2),
        ('Procesos Quirúrgicos en Gineco-Obstetricia', 'IQ-PQGO', 2, 'Práctica', 2),
        ('Procesos Asépticos II', 'IQ-PA2', 3, 'Práctica', 3),
        ('Metodología de la Investigación', 'IQ-MI', 2, 'Teórica', 2),
        ('Salud y Seguridad en el Trabajo', 'IQ-SST', 2, 'Teórica', 2),
        ('Práctica Hospitalaria I', 'IQ-PH1', 8, 'Práctica', 8),
        ('Procesos Quirúrgicos en Ortopedia', 'IQ-PQO', 3, 'Práctica', 3),
        ('Procesos Quirúrgicos en Neurocirugía', 'IQ-PQN', 3, 'Práctica', 3),
        ('Innovación y Tecnología', 'IQ-IT', 4, 'Teórica/Práctica', 4),
        ('Calidad en Servicios de Salud', 'IQ-CSS', 2, 'Teórica', 2),
        ('Práctica Hospitalaria II', 'IQ-PH2', 7, 'Práctica', 7),
        ('Procesos Quirúrgicos en Cirugía Maxilofacial', 'IQ-PQCM', 2, 'Práctica', 2),
        ('Procesos Quirúrgicos en Cirugía Plástica', 'IQ-PQCP', 2, 'Práctica', 2),
        ('Procesos Quirúrgicos en Oftalmología', 'IQ-PQOF', 2, 'Práctica', 2),
        ('Electiva de Profundización I', 'IQ-EP1', 2, 'Teórica/Práctica', 2),
        ('Investigación I', 'IQ-INV1', 3, 'Teórica', 3),
        ('Administración I', 'IQ-ADM1', 2, 'Teórica', 2),
        ('Salud Pública', 'IQ-SP', 2, 'Teórica', 2),
        ('Práctica Hospitalaria III', 'IQ-PH3', 8, 'Práctica', 8),
        ('Procesos Quirúrgicos en Otorrinolaringología', 'IQ-PQORL', 3, 'Práctica', 3),
        ('Procesos Quirúrgicos en Cardiovascular', 'IQ-PQCV', 3, 'Práctica', 3),
        ('Electiva de Profundización II', 'IQ-EP2', 5, 'Teórica/Práctica', 5),
        ('Investigación II', 'IQ-INV2', 2, 'Teórica', 2),
        ('Administración II', 'IQ-ADM2', 2, 'Teórica', 2),
        ('Práctica Hospitalaria IV', 'IQ-PH4', 8, 'Práctica', 8),
        ('Práctica de Administración', 'IQ-PAADM', 6, 'Práctica', 6),
        ('Salud Pública (Práctica Comunitaria)', 'IQ-SPPC', 4, 'Práctica', 4),
        ('Investigación III', 'IQ-INV3', 2, 'Teórica', 2),
        
        # === INGENIERÍA DE SISTEMAS (IS) ===
        ('Cálculo Diferencial', 'IS-CALD', 3, 'Teórica', 3),
        ('Física Mecánica', 'IS-FM', 3, 'Teórica', 3),
        ('Introducción a la Ingeniería', 'IS-II', 2, 'Teórica', 2),
        ('Lógica y Algoritmos', 'IS-LA', 3, 'Teórica/Práctica', 3),
        ('Lógica Matemática', 'IS-LM', 3, 'Teórica', 3),
        ('Competencias de Aprendizaje y Comunicación', 'IS-CAC', 3, 'Teórica', 3),
        ('Cátedra Unilibrista', 'IS-CU', 1, 'Teórica', 1),
        ('Cálculo Integral', 'IS-CALI', 3, 'Teórica', 3),
        ('Electricidad y Magnetismo y Laboratorio', 'IS-EML', 3, 'Teórica/Práctica', 3),
        ('Álgebra Lineal', 'IS-AL', 3, 'Teórica', 3),
        ('Pensamiento Sistémico', 'IS-PS', 2, 'Teórica', 2),
        ('Fundamentos de Programación', 'IS-FP', 3, 'Teórica/Práctica', 3),
        ('Electrónica Digital', 'IS-EDI', 2, 'Teórica/Práctica', 2),
        ('Electiva I', 'IS-ELEC1', 2, 'Teórica', 2),
        ('Cálculo Multivariado y Vectorial', 'IS-CMV', 3, 'Teórica', 3),
        ('Probabilidad y Estadística Descriptiva', 'IS-PED', 3, 'Teórica', 3),
        ('Diseño en Ingeniería', 'IS-DI', 3, 'Teórica/Práctica', 3),
        ('Estructuras de Datos', 'IS-EDAT', 3, 'Teórica/Práctica', 3),
        ('Arquitectura de Computadores', 'IS-AC', 3, 'Teórica/Práctica', 3),
        ('Ingeniería de Software I', 'IS-ISW1', 3, 'Teórica/Práctica', 3),
        ('Ecuaciones Diferenciales', 'IS-EDIF', 3, 'Teórica', 3),
        ('Cátedra de Sostenibilidad', 'IS-CS', 2, 'Teórica', 2),
        ('Constitución Política', 'IS-CP', 2, 'Teórica', 2),
        ('Fundamentos de Bases de Datos', 'IS-FBD', 3, 'Teórica/Práctica', 3),
        ('Programación I', 'IS-PROG1', 3, 'Teórica/Práctica', 3),
        ('Ingeniería de Software II', 'IS-ISW2', 3, 'Teórica/Práctica', 3),
        ('Electiva II', 'IS-ELEC2', 2, 'Teórica', 2),
        ('Matemáticas Discretas', 'IS-MD', 3, 'Teórica', 3),
        ('Sistemas Operativos', 'IS-SO', 3, 'Teórica/Práctica', 3),
        ('Sistemas de Bases de Datos', 'IS-SBD', 3, 'Teórica/Práctica', 3),
        ('Fundamentos de Economía', 'IS-FE', 3, 'Teórica', 3),
        ('Ingeniería de Software III', 'IS-ISW3', 3, 'Teórica/Práctica', 3),
        ('Programación II', 'IS-PROG2', 3, 'Teórica/Práctica', 3),
        ('Formulación y Evaluación de Proyectos', 'IS-FEP', 3, 'Teórica/Práctica', 3),
        ('Programación Web', 'IS-PWEB', 3, 'Teórica/Práctica', 3),
        ('Programación Lineal', 'IS-PL', 2, 'Teórica', 2),
        ('Arquitectura de Información', 'IS-AI', 2, 'Teórica/Práctica', 2),
        ('Redes de Computadores', 'IS-RC', 3, 'Teórica/Práctica', 3),
        ('Electiva III', 'IS-ELEC3', 2, 'Teórica', 2),
        ('Optativa I', 'IS-OPT1', 3, 'Teórica/Práctica', 3),
        ('Metodología de la Investigación', 'IS-MI', 3, 'Teórica', 3),
        ('Ética', 'IS-ET', 2, 'Teórica', 2),
        ('Seguridad de la Información', 'IS-SI', 2, 'Teórica/Práctica', 2),
        ('Inteligencia Artificial', 'IS-IA', 3, 'Teórica/Práctica', 3),
        ('Programación Móvil', 'IS-PM', 3, 'Teórica/Práctica', 3),
        ('Gestión de Proyectos de Ingeniería', 'IS-GPI', 2, 'Teórica', 2),
        ('Optativa II', 'IS-OPT2', 3, 'Teórica/Práctica', 3),
        ('Ingeniería Aplicada', 'IS-IAP', 3, 'Teórica/Práctica', 3),
        ('Arquitectura Empresarial', 'IS-AE', 3, 'Teórica', 3),
        ('Sistemas Integrados de Gestión', 'IS-SIG', 3, 'Teórica', 3),
        ('Práctica Empresarial', 'IS-PE', 3, 'Práctica', 3),
        ('Gerencia Estratégica', 'IS-GE', 3, 'Teórica', 3),
        ('Optativa III', 'IS-OPT3', 3, 'Teórica/Práctica', 3),
        
        # === INGENIERÍA INDUSTRIAL (II) ===
        ('Cálculo Diferencial', 'II-CALD', 3, 'Teórica', 3),
        ('Química General y Laboratorio', 'II-QGL', 3, 'Teórica/Práctica', 3),
        ('Introducción a la Ingeniería', 'II-II', 2, 'Teórica', 2),
        ('Lógica y Algoritmos', 'II-LA', 3, 'Teórica/Práctica', 3),
        ('Expresión Gráfica para Ingeniería', 'II-EGI', 3, 'Teórica/Práctica', 3),
        ('Competencias de Aprendizaje y Comunicación', 'II-CAC', 3, 'Teórica', 3),
        ('Cátedra Unilibrista', 'II-CU', 1, 'Teórica', 1),
        ('Cálculo Int egral', 'II-CALI', 3, 'Teórica', 3),
        ('Física Mecánica y Laboratorio', 'II-FML', 3, 'Teórica/Práctica', 3),
        ('Álgebra Lineal', 'II-AL', 3, 'Teórica', 3),
        ('Ciencia de los Materiales en la Industria', 'II-CMI', 2, 'Teórica/Práctica', 2),
        ('Lenguaje de Programación', 'II-LP', 3, 'Teórica/Práctica', 3),
        ('Contabilidad y Presupuesto', 'II-CP', 2, 'Teórica/Práctica', 2),
        ('Electiva I', 'II-ELEC1', 2, 'Teórica', 2),
        ('Cálculo Multivariado y Vectorial', 'II-CMV', 3, 'Teórica', 3),
        ('Electricidad y Magnetismo y Laboratorio', 'II-EML', 3, 'Teórica/Práctica', 3),
        ('Probabilidad y Estadística Descriptiva', 'II-PED', 3, 'Teórica', 3),
        ('Diseño en Ingeniería', 'II-DI', 2, 'Teórica/Práctica', 2),
        ('Gestión Organizacional', 'II-GO', 2, 'Teórica', 2),
        ('Fundamentos de Economía', 'II-FE', 3, 'Teórica', 3),
        ('Electiva II', 'II-ELEC2', 2, 'Teórica', 2),
        ('Ecuaciones Diferenciales', 'II-ED', 3, 'Teórica', 3),
        ('Termodinámica', 'II-TERM', 3, 'Teórica/Práctica', 3),
        ('Gerencia Estratégica', 'II-GE', 3, 'Teórica', 3),
        ('Control Estadístico de la Calidad', 'II-CEC', 3, 'Teórica/Práctica', 3),
        ('Procesos Industriales', 'II-PI', 3, 'Teórica/Práctica', 3),
        ('Costos de Operación', 'II-CO', 3, 'Teórica', 3),
        ('Investigación Operativa I', 'II-IO1', 3, 'Teórica/Práctica', 3),
        ('Sistemas Integrados de Gestión', 'II-SIG', 2, 'Teórica', 2),
        ('Diseño de Productos y Servicios', 'II-DPS', 3, 'Teórica/Práctica', 3),
        ('Ingeniería de Métodos', 'II-IM', 3, 'Teórica/Práctica', 3),
        ('Ingeniería Económica', 'II-IE', 3, 'Teórica', 3),
        ('Cátedra de Sostenibilidad', 'II-CS', 2, 'Teórica', 2),
        ('Electiva III', 'II-ELEC3', 2, 'Teórica', 2),
        ('Investigación Operativa II', 'II-IO2', 3, 'Teórica/Práctica', 3),
        ('Planeación y Control de la Producción y Operaciones', 'II-PCPO', 3, 'Teórica/Práctica', 3),
        ('Mercadeo', 'II-MER', 3, 'Teórica', 3),
        ('Gestión de la Tecnología', 'II-GT', 3, 'Teórica', 3),
        ('Finanzas', 'II-FIN', 3, 'Teórica', 3),
        ('Optativa I', 'II-OPT1', 3, 'Teórica/Práctica', 3),
        ('Modelos Matemáticos Estocásticos', 'II-MME', 3, 'Teórica', 3),
        ('Seguridad y Salud en el Trabajo', 'II-SST', 2, 'Teórica', 2),
        ('Formulación y Evaluación de Proyectos', 'II-FEP', 3, 'Teórica/Práctica', 3),
        ('Metodología de la Investigación', 'II-MI', 3, 'Teórica', 3),
        ('Constitución Política', 'II-CPOL', 2, 'Teórica', 2),
        ('Ética', 'II-ET', 2, 'Teórica', 2),
        ('Optativa II', 'II-OPT2', 3, 'Teórica/Práctica', 3),
        ('Diseño de Instalaciones Industriales y de Servicios', 'II-DIIS', 3, 'Teórica/Práctica', 3),
        ('Logística y Cadena de Suministros', 'II-LCS', 3, 'Teórica/Práctica', 3),
        ('Ingeniería Aplicada', 'II-IA', 3, 'Teórica/Práctica', 3),
        ('Simulación de Procesos', 'II-SP', 3, 'Teórica/Práctica', 3),
        ('Práctica Empresarial', 'II-PE', 3, 'Práctica', 3),
        ('Optativa III', 'II-OPT3', 3, 'Teórica/Práctica', 3),
        
        # === DERECHO (DER) ===
        ('Introducción al Derecho', 'DER-ID', 3, 'Teórica', 3),
        ('Derecho Romano', 'DER-DR', 3, 'Teórica', 3),
        ('Historia del Derecho', 'DER-HD', 2, 'Teórica', 2),
        ('Teoría del Estado', 'DER-TE', 3, 'Teórica', 3),
        ('Competencias Comunicativas', 'DER-CC', 2, 'Teórica', 2),
        ('Cátedra Unilibrista', 'DER-CU', 1, 'Teórica', 1),
        ('Derecho Constitucional I', 'DER-DC1', 3, 'Teórica', 3),
        ('Teoría General del Derecho', 'DER-TGD', 3, 'Teórica', 3),
        ('Derecho Civil Personas', 'DER-DCP', 3, 'Teórica', 3),
        ('Sociología Jurídica', 'DER-SJ', 2, 'Teórica', 2),
        ('Metodología de la Investigación', 'DER-MI', 3, 'Teórica', 3),
        ('Derecho Constitucional II', 'DER-DC2', 3, 'Teórica', 3),
        ('Derecho Civil Bienes', 'DER-DCB', 3, 'Teórica', 3),
        ('Derecho Penal General', 'DER-DPG', 3, 'Teórica', 3),
        ('Filosofía del Derecho', 'DER-FD', 2, 'Teórica', 2),
        ('Electiva I', 'DER-ELEC1', 2, 'Teórica', 2),
        ('Derecho Civil Obligaciones', 'DER-DCO', 3, 'Teórica', 3),
        ('Derecho Penal Especial', 'DER-DPE', 3, 'Teórica', 3),
        ('Derecho Administrativo I', 'DER-DA1', 3, 'Teórica', 3),
        ('Hermenéutica Jurídica', 'DER-HJ', 2, 'Teórica', 2),
        ('Electiva II', 'DER-ELEC2', 2, 'Teórica', 2),
        ('Derecho Civil Contratos', 'DER-DCC', 3, 'Teórica', 3),
        ('Derecho Procesal Civil I', 'DER-DPC1', 3, 'Teórica', 3),
        ('Derecho Administrativo II', 'DER-DA2', 3, 'Teórica', 3),
        ('Derecho Laboral Individual', 'DER-DLI', 3, 'Teórica', 3),
        ('Electiva III', 'DER-ELEC3', 2, 'Teórica', 2),
        ('Derecho Procesal Civil II', 'DER-DPC2', 3, 'Teórica', 3),
        ('Derecho Laboral Colectivo', 'DER-DLC', 3, 'Teórica', 3),
        ('Derecho Comercial I', 'DER-DCOM1', 3, 'Teórica', 3),
        ('Derecho Procesal Penal', 'DER-DPP', 3, 'Teórica', 3),
        ('Ética Profesional', 'DER-EP', 2, 'Teórica', 2),
        ('Derecho Comercial II', 'DER-DCOM2', 3, 'Teórica', 3),
        ('Derecho Probatorio', 'DER-DPR', 3, 'Teórica', 3),
        ('Derecho Internacional Público', 'DER-DIP', 3, 'Teórica', 3),
        ('Derecho Tributario', 'DER-DT', 3, 'Teórica', 3),
        ('Optativa I', 'DER-OPT1', 2, 'Teórica', 2),
        ('Derecho Internacional Privado', 'DER-DIPR', 3, 'Teórica', 3),
        ('Derecho Financiero', 'DER-DF', 3, 'Teórica', 3),
        ('Derecho Procesal Administrativo', 'DER-DPA', 3, 'Teórica', 3),
        ('Consultorio Jurídico I', 'DER-CJ1', 3, 'Práctica', 3),
        ('Optativa II', 'DER-OPT2', 2, 'Teórica', 2),
        ('Consultorio Jurídico II', 'DER-CJ2', 3, 'Práctica', 3),
        ('Mecanismos Alternativos de Solución de Conflictos', 'DER-MASC', 2, 'Teórica/Práctica', 2),
        ('Seminario de Grado', 'DER-SG', 2, 'Teórica', 2),
        ('Práctica Jurídica', 'DER-PJ', 4, 'Práctica', 4),
        ('Optativa III', 'DER-OPT3', 2, 'Teórica', 2),
        
        # === BACTERIOLOGÍA (BAC) ===
        ('Biología', 'BAC-BIO', 2, 'Teórica', 2),
        ('Morfofisiología I', 'BAC-MF1', 3, 'Teórica/Práctica', 3),
        ('Biofísica', 'BAC-BF', 2, 'Teórica', 2),
        ('Química', 'BAC-QUI', 2, 'Teórica', 2),
        ('Competencias Comunicativas I', 'BAC-CC1', 2, 'Teórica', 2),
        ('Sociedad, Sector Salud y Comunidad', 'BAC-SSSC', 2, 'Teórica', 2),
        ('Cátedra Unilibrista', 'BAC-CU', 1, 'Teórica', 1),
        ('Bioquímica', 'BAC-BQ', 2, 'Teórica', 2),
        ('Morfofisiología II', 'BAC-MF2', 3, 'Teórica/Práctica', 3),
        ('Microbiología General', 'BAC-MG', 3, 'Teórica/Práctica', 3),
        ('Fundamentos de Psicología', 'BAC-FPS', 2, 'Teórica', 2),
        ('Competencias Comunicativas II', 'BAC-CC2', 2, 'Teórica', 2),
        ('Bioestadística e Informática', 'BAC-BEI', 2, 'Teórica/Práctica', 2),
        ('Ética General y Bioética', 'BAC-EGB', 3, 'Teórica', 3),
        ('Inmunología', 'BAC-INM', 3, 'Teórica/Práctica', 3),
        ('Hematología', 'BAC-HEM', 3, 'Teórica/Práctica', 3),
        ('Parasitología', 'BAC-PAR', 3, 'Teórica/Práctica', 3),
        ('Bacteriología Clínica I', 'BAC-BC1', 3, 'Teórica/Práctica', 3),
        ('Investigación Clínica Epidemiológica', 'BAC-ICE', 2, 'Teórica', 2),
        ('Socioantropología', 'BAC-SA', 2, 'Teórica', 2),
        ('Inmunohematología', 'BAC-IH', 3, 'Teórica/Práctica', 3),
        ('Bacteriología Clínica II', 'BAC-BC2', 3, 'Teórica/Práctica', 3),
        ('Virología', 'BAC-VIR', 3, 'Teórica/Práctica', 3),
        ('Micología', 'BAC-MIC', 2, 'Teórica/Práctica', 2),
        ('Alimentación y Salud', 'BAC-AS', 2, 'Teórica', 2),
        ('Constitución Nacional', 'BAC-CN', 2, 'Teórica', 2),
        ('Citología', 'BAC-CIT', 3, 'Teórica/Práctica', 3),
        ('Bacteriología Clínica III', 'BAC-BC3', 3, 'Teórica/Práctica', 3),
        ('Microbiología de Alimentos', 'BAC-MA', 3, 'Teórica/Práctica', 3),
        ('Metodología de la Investigación', 'BAC-MI', 2, 'Teórica', 2),
        ('Toxicología', 'BAC-TOX', 2, 'Teórica', 2),
        ('Electiva Complementaria I', 'BAC-EC1', 1, 'Teórica', 1),
        ('Salud Ambiental y Ocupacional', 'BAC-SAO', 2, 'Teórica', 2),
        ('Práctica Hospitalaria I', 'BAC-PH1', 8, 'Práctica', 8),
        ('Biotecnología', 'BAC-BT', 3, 'Teórica/Práctica', 3),
        ('Electiva de Profundización I', 'BAC-EP1', 2, 'Teórica/Práctica', 2),
        ('Investigación I', 'BAC-INV1', 3, 'Teórica', 3),
        ('Gestión de la Calidad', 'BAC-GC', 2, 'Teórica', 2),
        ('Práctica Hospitalaria II', 'BAC-PH2', 8, 'Práctica', 8),
        ('Microbiología del Suelo y Agua', 'BAC-MSA', 3, 'Teórica/Práctica', 3),
        ('Electiva de Profundización II', 'BAC-EP2', 5, 'Teórica/Práctica', 5),
        ('Investigación II', 'BAC-INV2', 2, 'Teórica', 2),
        ('Administración I', 'BAC-ADM1', 2, 'Teórica', 2),
        ('Seminarios de Investigación en Bacteriología', 'BAC-SIB', 2, 'Teórica', 2),
        ('Práctica en Administración y Administración de Laboratorios', 'BAC-PAAL', 6, 'Práctica', 6),
        ('Práctica Hospitalaria III', 'BAC-PH3', 8, 'Práctica', 8),
        ('Salud Pública (Práctica Comunitaria)', 'BAC-SPPC', 4, 'Práctica', 4),
        ('Investigación III', 'BAC-INV3', 2, 'Teórica', 2),
        ('Administración II', 'BAC-ADM2', 2, 'Teórica', 2),
        
        # === MICROBIOLOGÍA (MIC) ===
        ('Biología', 'MIC-BIO', 2, 'Teórica', 2),
        ('Morfofisiología I', 'MIC-MF1', 3, 'Teórica/Práctica', 3),
        ('Biofísica', 'MIC-BF', 2, 'Teórica', 2),
        ('Química', 'MIC-QUI', 2, 'Teórica', 2),
        ('Competencias Comunicativas I', 'MIC-CC1', 2, 'Teórica', 2),
        ('Sociedad, Sector Salud y Comunidad', 'MIC-SSSC', 2, 'Teórica', 2),
        ('Cátedra Unilibrista', 'MIC-CU', 1, 'Teórica', 1),
        ('Bioquímica', 'MIC-BQ', 2, 'Teórica', 2),
        ('Morfofisiología II', 'MIC-MF2', 3, 'Teórica/Práctica', 3),
        ('Microbiología General', 'MIC-MG', 3, 'Teórica/Práctica', 3),
        ('Fundamentos de Psicología', 'MIC-FPS', 2, 'Teórica', 2),
        ('Competencias Comunicativas II', 'MIC-CC2', 2, 'Teórica', 2),
        ('Bioestadística e Informática', 'MIC-BEI', 2, 'Teórica/Práctica', 2),
        ('Ética General y Bioética', 'MIC-EGB', 3, 'Teórica', 3),
        ('Inmunología', 'MIC-INM', 3, 'Teórica/Práctica', 3),
        ('Hematología', 'MIC-HEM', 3, 'Teórica/Práctica', 3),
        ('Parasitología', 'MIC-PAR', 3, 'Teórica/Práctica', 3),
        ('Bacteriología Clínica I', 'MIC-BC1', 3, 'Teórica/Práctica', 3),
        ('Investigación Clínica Epidemiológica', 'MIC-ICE', 2, 'Teórica', 2),
        ('Socioantropología', 'MIC-SA', 2, 'Teórica', 2),
        ('Inmunohematología', 'MIC-IH', 3, 'Teórica/Práctica', 3),
        ('Bacteriología Clínica II', 'MIC-BC2', 3, 'Teórica/Práctica', 3),
        ('Virología', 'MIC-VIR', 3, 'Teórica/Práctica', 3),
        ('Micología', 'MIC-MIC', 2, 'Teórica/Práctica', 2),
        ('Alimentación y Salud', 'MIC-AS', 2, 'Teórica', 2),
        ('Constitución Nacional', 'MIC-CN', 2, 'Teórica', 2),
        ('Genética Microbiana', 'MIC-GM', 3, 'Teórica/Práctica', 3),
        ('Bacteriología Clínica III', 'MIC-BC3', 3, 'Teórica/Práctica', 3),
        ('Microbiología Ambiental', 'MIC-MA', 3, 'Teórica/Práctica', 3),
        ('Metodología de la Investigación', 'MIC-MI', 2, 'Teórica', 2),
        ('Fisiología Microbiana', 'MIC-FM', 2, 'Teórica/Práctica', 2),
        ('Electiva Complementaria I', 'MIC-EC1', 1, 'Teórica', 1),
        ('Microbiología Industrial', 'MIC-MIND', 3, 'Teórica/Práctica', 3),
        ('Práctica Hospitalaria I', 'MIC-PH1', 8, 'Práctica', 8),
        ('Microbiología Molecular', 'MIC-MM', 3, 'Teórica/Práctica', 3),
        ('Electiva de Profundización I', 'MIC-EP1', 2, 'Teórica/Práctica', 2),
        ('Investigación I', 'MIC-INV1', 3, 'Teórica', 3),
        ('Gestión de la Calidad', 'MIC-GC', 2, 'Teórica', 2),
        ('Práctica Hospitalaria II', 'MIC-PH2', 8, 'Práctica', 8),
        ('Cultivo de Tejidos', 'MIC-CT', 3, 'Teórica/Práctica', 3),
        ('Microbiología de Alimentos', 'MIC-MALIM', 3, 'Teórica/Práctica', 3),
        ('Electiva de Profundización II', 'MIC-EP2', 5, 'Teórica/Práctica', 5),
        ('Investigación II', 'MIC-INV2', 2, 'Teórica', 2),
        ('Administración I', 'MIC-ADM1', 2, 'Teórica', 2),
        ('Seminarios de Investigación en Microbiología', 'MIC-SIM', 2, 'Teórica', 2),
        ('Práctica en Administración y Administración de Laboratorios', 'MIC-PAAL', 6, 'Práctica', 6),
        ('Práctica Hospitalaria III', 'MIC-PH3', 8, 'Práctica', 8),
        ('Salud Pública (Práctica Comunitaria)', 'MIC-SPPC', 4, 'Práctica', 4),
        ('Investigación III', 'MIC-INV3', 2, 'Teórica', 2),
        ('Administración II', 'MIC-ADM2', 2, 'Teórica', 2),
        
        # === FISIOTERAPIA (FIS) ===
        ('Biología', 'FIS-BIO', 2, 'Teórica', 2),
        ('Morfofisiología I', 'FIS-MF1', 3, 'Teórica/Práctica', 3),
        ('Biofísica', 'FIS-BF', 2, 'Teórica', 2),
        ('Química', 'FIS-QUI', 2, 'Teórica', 2),
        ('Competencias Comunicativas I', 'FIS-CC1', 2, 'Teórica', 2),
        ('Antropología y Medio Ambiente', 'FIS-AMA', 2, 'Teórica', 2),
        ('Cátedra Unilibrista', 'FIS-CU', 1, 'Teórica', 1),
        ('Fundamentos de Fisioterapia', 'FIS-FF', 2, 'Teórica', 2),
        ('Bioquímica', 'FIS-BQ', 2, 'Teórica', 2),
        ('Morfofisiología II', 'FIS-MF2', 3, 'Teórica/Práctica', 3),
        ('Kinesiología', 'FIS-KIN', 3, 'Teórica/Práctica', 3),
        ('Fundamentos de Psicología', 'FIS-FPS', 2, 'Teórica', 2),
        ('Competencias Comunicativas II', 'FIS-CC2', 2, 'Teórica', 2),
        ('Bioestadística e Informática', 'FIS-BEI', 2, 'Teórica/Práctica', 2),
        ('Ética General y Deontología de la Fisioterapia', 'FIS-EGDF', 3, 'Teórica', 3),
        ('Semiología Médico Quirúrgica', 'FIS-SMQ', 2, 'Teórica/Práctica', 2),
        ('Morfofisiología III', 'FIS-MF3', 3, 'Teórica/Práctica', 3),
        ('Cinesiterapia', 'FIS-CIN', 3, 'Teórica/Práctica', 3),
        ('Masoterapia', 'FIS-MAS', 3, 'Teórica/Práctica', 3),
        ('Mecanoterapia', 'FIS-MEC', 3, 'Teórica/Práctica', 3),
        ('Investigación Clínica Epidemiológica', 'FIS-ICE', 2, 'Teórica', 2),
        ('Socioantropología', 'FIS-SA', 2, 'Teórica', 2),
        ('Fisioterapia en Pediatría', 'FIS-FPE', 3, 'Teórica/Práctica', 3),
        ('Electroterapia', 'FIS-ELE', 3, 'Teórica/Práctica', 3),
        ('Fisioterapia Cardiopulmonar', 'FIS-FCP', 3, 'Teórica/Práctica', 3),
        ('Hidrocinesiterapia', 'FIS-HID', 2, 'Teórica/Práctica', 2),
        ('Constitución Nacional', 'FIS-CN', 2, 'Teórica', 2),
        ('Electiva Complementaria I', 'FIS-EC1', 1, 'Teórica', 1),
        ('Fisioterapia Neurológica', 'FIS-FNE', 3, 'Teórica/Práctica', 3),
        ('Fisioterapia en Ortopedia y Traumatología', 'FIS-FOT', 3, 'Teórica/Práctica', 3),
        ('Fisioterapia en Geriatría', 'FIS-FGE', 3, 'Teórica/Práctica', 3),
        ('Agentes Térmicos', 'FIS-AT', 2, 'Teórica/Práctica', 2),
        ('Metodología de la Investigación', 'FIS-MI', 2, 'Teórica', 2),
        ('Salud y Seguridad en el Trabajo', 'FIS-SST', 2, 'Teórica', 2),
        ('Práctica Hospitalaria I', 'FIS-PH1', 8, 'Práctica', 8),
        ('Fisioterapia Dermatofuncional', 'FIS-FDF', 2, 'Teórica/Práctica', 2),
        ('Fisioterapia en el Deporte', 'FIS-FDE', 2, 'Teórica/Práctica', 2),
        ('Electiva de Profundización I', 'FIS-EP1', 2, 'Teórica/Práctica', 2),
        ('Investigación I', 'FIS-INV1', 3, 'Teórica', 3),
        ('Administración I', 'FIS-ADM1', 2, 'Teórica', 2),
        ('Calidad en Servicios de Salud', 'FIS-CSS', 2, 'Teórica', 2),
        ('Práctica Hospitalaria II', 'FIS-PH2', 8, 'Práctica', 8),
        ('Fisioterapia Manual Ortopédica', 'FIS-FMO', 3, 'Teórica/Práctica', 3),
        ('Electiva de Profundización II', 'FIS-EP2', 5, 'Teórica/Práctica', 5),
        ('Investigación II', 'FIS-INV2', 2, 'Teórica', 2),
        ('Administración II', 'FIS-ADM2', 2, 'Teórica', 2),
        ('Práctica Hospitalaria III', 'FIS-PH3', 8, 'Práctica', 8),
        ('Práctica de Administración', 'FIS-PAADM', 6, 'Práctica', 6),
        ('Salud Pública (Práctica Comunitaria)', 'FIS-SPPC', 4, 'Práctica', 4),
        ('Investigación III', 'FIS-INV3', 2, 'Teórica', 2),
        
        # === MEDICINA (MED) ===
        ('Biología Celular y Molecular', 'MED-BCM', 3, 'Teórica', 3),
        ('Química', 'MED-QUI', 3, 'Teórica', 3),
        ('Morfología I', 'MED-MORF1', 4, 'Teórica/Práctica', 4),
        ('Competencias Comunicativas I', 'MED-CC1', 2, 'Teórica', 2),
        ('Antropología y Medio Ambiente', 'MED-AMA', 2, 'Teórica', 2),
        ('Práctica Social I', 'MED-PS1', 2, 'Práctica', 2),
        ('Cátedra Unilibrista', 'MED-CU', 1, 'Teórica', 1),
        ('Bioquímica', 'MED-BQ', 3, 'Teórica', 3),
        ('Morfología II', 'MED-MORF2', 4, 'Teórica/Práctica', 4),
        ('Fisiología I', 'MED-FIS1', 3, 'Teórica/Práctica', 3),
        ('Competencias Comunicativas II', 'MED-CC2', 2, 'Teórica', 2),
        ('Bioestadística e Informática', 'MED-BEI', 2, 'Teórica/Práctica', 2),
        ('Práctica Social II', 'MED-PS2', 2, 'Práctica', 2),
        ('Fisiología II', 'MED-FIS2', 3, 'Teórica/Práctica', 3),
        ('Microbiología y Parasitología', 'MED-MP', 4, 'Teórica/Práctica', 4),
        ('Genética', 'MED-GEN', 2, 'Teórica', 2),
        ('Fundamentos de Psicología', 'MED-FPS', 2, 'Teórica', 2),
        ('Ética General y Bioética', 'MED-EGB', 2, 'Teórica', 2),
        ('Práctica Social III', 'MED-PS3', 2, 'Práctica', 2),
        ('Inmunología', 'MED-INM', 2, 'Teórica/Práctica', 2),
        ('Semiología I', 'MED-SEM1', 4, 'Teórica/Práctica', 4),
        ('Patología I', 'MED-PAT1', 3, 'Teórica/Práctica', 3),
        ('Nutrición', 'MED-NUT', 2, 'Teórica', 2),
        ('Epidemiología I', 'MED-EPI1', 2, 'Teórica', 2),
        ('Socioantropología', 'MED-SA', 2, 'Teórica', 2),
        ('Semiología II', 'MED-SEM2', 4, 'Teórica/Práctica', 4),
        ('Patología II', 'MED-PAT2', 3, 'Teórica/Práctica', 3),
        ('Farmacología I', 'MED-FARM1', 3, 'Teórica', 3),
        ('Medicina Preventiva', 'MED-MP2', 2, 'Teórica', 2),
        ('Electiva Complementaria I', 'MED-EC1', 1, 'Teórica', 1),
        ('Medicina Interna I', 'MED-MI1', 4, 'Teórica/Práctica', 4),
        ('Cirugía I', 'MED-CIR1', 4, 'Teórica/Práctica', 4),
        ('Farmacología II', 'MED-FARM2', 3, 'Teórica', 3),
        ('Metodología de la Investigación', 'MED-MINV', 2, 'Teórica', 2),
        ('Constitución Nacional', 'MED-CN', 2, 'Teórica', 2),
        ('Medicina Interna II', 'MED-MI2', 4, 'Teórica/Práctica', 4),
        ('Cirugía II', 'MED-CIR2', 4, 'Teórica/Práctica', 4),
        ('Pediatría I', 'MED-PED1', 4, 'Teórica/Práctica', 4),
        ('Ginecología y Obstetricia I', 'MED-GO1', 4, 'Teórica/Práctica', 4),
        ('Epidemiología II', 'MED-EPI2', 2, 'Teórica', 2),
        ('Medicina Interna III', 'MED-MI3', 4, 'Teórica/Práctica', 4),
        ('Cirugía III', 'MED-CIR3', 4, 'Teórica/Práctica', 4),
        ('Pediatría II', 'MED-PED2', 4, 'Teórica/Práctica', 4),
        ('Ginecología y Obstetricia II', 'MED-GO2', 4, 'Teórica/Práctica', 4),
        ('Investigación I', 'MED-INV1', 3, 'Teórica', 3),
        ('Psiquiatría', 'MED-PSI', 4, 'Teórica/Práctica', 4),
        ('Ortopedia', 'MED-ORT', 3, 'Teórica/Práctica', 3),
        ('Urología', 'MED-URO', 2, 'Teórica/Práctica', 2),
        ('Oftalmología', 'MED-OFT', 2, 'Teórica/Práctica', 2),
        ('Otorrinolaringología', 'MED-ORL', 2, 'Teórica/Práctica', 2),
        ('Investigación II', 'MED-INV2', 2, 'Teórica', 2),
        ('Medicina Legal', 'MED-ML', 2, 'Teórica/Práctica', 2),
        ('Dermatología', 'MED-DER', 2, 'Teórica/Práctica', 2),
        ('Anestesiología', 'MED-ANE', 2, 'Teórica/Práctica', 2),
        ('Radiología', 'MED-RAD', 2, 'Teórica/Práctica', 2),
        ('Electiva de Profundización I', 'MED-EP1', 2, 'Teórica/Práctica', 2),
        ('Investigación III', 'MED-INV3', 2, 'Teórica', 2),
        ('Internado Rural', 'MED-IR', 12, 'Práctica', 12),
    ]

