"""
Seeder de relaciones Asignatura-Programa.
"""

from asignaturas.models import Asignatura, AsignaturaPrograma
from programas.models import Programa


def create_asignaturas_programa(stdout, style):
    """Crear relaciones entre asignaturas y programas con semestre y componente formativo"""
    stdout.write('  → Creando relaciones asignatura-programa...')
    stdout.write('     Este proceso puede tomar varios segundos...')
    
    # Mapeo de componentes formativos
    componentes_map = {
        'Básica': 'Básica',
        'Profesional': 'Profesional',
        'Humanística': 'Humanística',
        'Práctico': 'Práctico',
        'Optativa': 'Optativa',
        'Electiva': 'Electiva'
    }
    
    # Formato: (nombre_programa, codigo_asignatura, semestre, componente_formativo)
    relaciones_data = [
        # === INGENIERÍA DE SISTEMAS ===
        ('Ingeniería de Sistemas', 'IS-CALD', 1, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-FM', 1, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-II', 1, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-LA', 1, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-LM', 1, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-CAC', 1, 'Humanística'),
        ('Ingeniería de Sistemas', 'IS-CU', 1, 'Humanística'),
        ('Ingeniería de Sistemas', 'IS-CALI', 2, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-EML', 2, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-AL', 2, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-PS', 2, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-FP', 2, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-EDI', 2, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-ELEC1', 2, 'Electiva'),
        ('Ingeniería de Sistemas', 'IS-CMV', 3, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-PED', 3, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-DI', 3, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-EDAT', 3, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-AC', 3, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-ISW1', 3, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-EDIF', 4, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-CS', 4, 'Humanística'),
        ('Ingeniería de Sistemas', 'IS-CP', 4, 'Humanística'),
        ('Ingeniería de Sistemas', 'IS-FBD', 4, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-PROG1', 4, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-ISW2', 4, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-ELEC2', 4, 'Electiva'),
        ('Ingeniería de Sistemas', 'IS-MD', 5, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-SO', 5, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-SBD', 5, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-FE', 5, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-ISW3', 5, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-PROG2', 5, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-FEP', 6, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-PWEB', 6, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-PL', 6, 'Básica'),
        ('Ingeniería de Sistemas', 'IS-AI', 6, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-RC', 6, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-ELEC3', 6, 'Electiva'),
        ('Ingeniería de Sistemas', 'IS-OPT1', 6, 'Optativa'),
        ('Ingeniería de Sistemas', 'IS-MI', 7, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-ET', 7, 'Humanística'),
        ('Ingeniería de Sistemas', 'IS-SI', 7, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-IA', 7, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-PM', 7, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-GPI', 7, 'Profesional'),
       ('Ingeniería de Sistemas', 'IS-OPT2', 7, 'Optativa'),
        ('Ingeniería de Sistemas', 'IS-IAP', 8, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-AE', 8, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-SIG', 8, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-PE', 8, 'Práctico'),
        ('Ingeniería de Sistemas', 'IS-GE', 8, 'Profesional'),
        ('Ingeniería de Sistemas', 'IS-OPT3', 8, 'Optativa'),
        
        # === INGENIERÍA INDUSTRIAL ===
        ('Ingeniería Industrial', 'II-CALD', 1, 'Básica'),
        ('Ingeniería Industrial', 'II-QGL', 1, 'Básica'),
        ('Ingeniería Industrial', 'II-II', 1, 'Profesional'),
        ('Ingeniería Industrial', 'II-LA', 1, 'Básica'),
        ('Ingeniería Industrial', 'II-EGI', 1, 'Profesional'),
        ('Ingeniería Industrial', 'II-CAC', 1, 'Humanística'),
        ('Ingeniería Industrial', 'II-CU', 1, 'Humanística'),
        ('Ingeniería Industrial', 'II-CALI', 2, 'Básica'),
        ('Ingeniería Industrial', 'II-FML', 2, 'Básica'),
        ('Ingeniería Industrial', 'II-AL', 2, 'Básica'),
        ('Ingeniería Industrial', 'II-CMI', 2, 'Profesional'),
        ('Ingeniería Industrial', 'II-LP', 2, 'Profesional'),
        ('Ingeniería Industrial', 'II-CP', 2, 'Profesional'),
        ('Ingeniería Industrial', 'II-ELEC1', 2, 'Electiva'),
        ('Ingeniería Industrial', 'II-CMV', 3, 'Básica'),
        ('Ingeniería Industrial', 'II-EML', 3, 'Básica'),
        ('Ingeniería Industrial', 'II-PED', 3, 'Básica'),
        ('Ingeniería Industrial', 'II-DI', 3, 'Profesional'),
        ('Ingeniería Industrial', 'II-GO', 3, 'Profesional'),
        ('Ingeniería Industrial', 'II-FE', 3, 'Básica'),
        ('Ingeniería Industrial', 'II-ELEC2', 3, 'Electiva'),
        ('Ingeniería Industrial', 'II-ED', 4, 'Básica'),
        ('Ingeniería Industrial', 'II-TERM', 4, 'Básica'),
        ('Ingeniería Industrial', 'II-GE', 4, 'Profesional'),
        ('Ingeniería Industrial', 'II-CEC', 4, 'Profesional'),
        ('Ingeniería Industrial', 'II-PI', 4, 'Profesional'),
        ('Ingeniería Industrial', 'II-CO', 4, 'Profesional'),
        ('Ingeniería Industrial', 'II-IO1', 5, 'Profesional'),
        ('Ingeniería Industrial', 'II-SIG', 5, 'Profesional'),
        ('Ingeniería Industrial', 'II-DPS', 5, 'Profesional'),
        ('Ingeniería Industrial', 'II-IM', 5, 'Profesional'),
        ('Ingeniería Industrial', 'II-IE', 5, 'Profesional'),
        ('Ingeniería Industrial', 'II-CS', 5, 'Humanística'),
        ('Ingeniería Industrial', 'II-ELEC3', 5, 'Electiva'),
        ('Ingeniería Industrial', 'II-IO2', 6, 'Profesional'),
        ('Ingeniería Industrial', 'II-PCPO', 6, 'Profesional'),
        ('Ingeniería Industrial', 'II-MER', 6, 'Profesional'),
        ('Ingeniería Industrial', 'II-GT', 6, 'Profesional'),
        ('Ingeniería Industrial', 'II-FIN', 6, 'Profesional'),
        ('Ingeniería Industrial', 'II-OPT1', 6, 'Optativa'),
        ('Ingeniería Industrial', 'II-MME', 7, 'Básica'),
        ('Ingeniería Industrial', 'II-SST', 7, 'Profesional'),
        ('Ingeniería Industrial', 'II-FEP', 7, 'Profesional'),
        ('Ingeniería Industrial', 'II-MI', 7, 'Profesional'),
        ('Ingeniería Industrial', 'II-CPOL', 7, 'Humanística'),
        ('Ingeniería Industrial', 'II-ET', 7, 'Humanística'),
        ('Ingeniería Industrial', 'II-OPT2', 7, 'Optativa'),
        ('Ingeniería Industrial', 'II-DIIS', 8, 'Profesional'),
        ('Ingeniería Industrial', 'II-LCS', 8, 'Profesional'),
        ('Ingeniería Industrial', 'II-IA', 8, 'Profesional'),
        ('Ingeniería Industrial', 'II-SP', 8, 'Profesional'),
        ('Ingeniería Industrial', 'II-PE', 8, 'Práctico'),
        ('Ingeniería Industrial', 'II-OPT3', 8, 'Optativa'),
        
        # === NEGOCIOS INTERNACIONALES ===
        ('Administración de Negocios Internacionales', 'NI-FM', 1, 'Básica'),
        ('Administración de Negocios Internacionales', 'NI-FNI', 1, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-FE', 1, 'Básica'),
        ('Administración de Negocios Internacionales', 'NI-CF', 1, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-EVE', 1, 'Humanística'),
        ('Administración de Negocios Internacionales', 'NI-CU', 1, 'Humanística'),
        ('Administración de Negocios Internacionales', 'NI-CAL', 2, 'Básica'),
        ('Administración de Negocios Internacionales', 'NI-EE', 2, 'Básica'),
        ('Administración de Negocios Internacionales', 'NI-SC', 2, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-ED', 2, 'Básica'),
        ('Administración de Negocios Internacionales', 'NI-DC', 2, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-ELEC1', 2, 'Electiva'),
        ('Administración de Negocios Internacionales', 'NI-CEN', 3, 'Básica'),
        ('Administración de Negocios Internacionales', 'NI-EI2', 3, 'Básica'),
        ('Administración de Negocios Internacionales', 'NI-FMERC', 3, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-LA', 3, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-CNG', 3, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-ELEC2', 3, 'Electiva'),
        ('Administración de Negocios Internacionales', 'NI-FI', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-LDFI', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-IM', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-DCI', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-GPO', 4, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-SNC', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-DL', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-PE', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-FGP', 5, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-ELEC3', 5, 'Electiva'),
        ('Administración de Negocios Internacionales', 'NI-IMKT', 6, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-GTH', 6, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-GCE', 6, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-MI', 6, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-OE1', 6, 'Optativa'),
        ('Administración de Negocios Internacionales', 'NI-GI', 7, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-AF', 7, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-EPRS', 7, 'Humanística'),
        ('Administración de Negocios Internacionales', 'NI-PI', 7, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-OE2', 7, 'Optativa'),
        ('Administración de Negocios Internacionales', 'NI-GEX', 8, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-SG', 8, 'Profesional'),
        ('Administración de Negocios Internacionales', 'NI-GLOB', 8, 'Humanística'),
        ('Administración de Negocios Internacionales', 'NI-OE3', 8, 'Optativa'),
        
        # === CONTADURÍA PÚBLICA ===
        ('Contaduría Pública', 'CP-FM', 1, 'Básica'),
        ('Contaduría Pública', 'CP-FA', 1, 'Profesional'),
        ('Contaduría Pública', 'CP-CF', 1, 'Profesional'),
        ('Contaduría Pública', 'CP-FE', 1, 'Básica'),
        ('Contaduría Pública', 'CP-EVE', 1, 'Humanística'),
        ('Contaduría Pública', 'CP-CU', 1, 'Humanística'),
        ('Contaduría Pública', 'CP-CAL1', 2, 'Básica'),
        ('Contaduría Pública', 'CP-CEAI', 2, 'Profesional'),
        ('Contaduría Pública', 'CP-EE', 2, 'Básica'),
        ('Contaduría Pública', 'CP-DC', 2, 'Profesional'),
        ('Contaduría Pública', 'CP-ED', 2, 'Básica'),
        ('Contaduría Pública', 'CP-ELEC1', 2, 'Electiva'),
        ('Contaduría Pública', 'CP-EI2', 3, 'Básica'),
        ('Contaduría Pública', 'CP-SC', 3, 'Profesional'),
        ('Contaduría Pública', 'CP-CEN', 3, 'Básica'),
        ('Contaduría Pública', 'CP-DLSS', 3, 'Profesional'),
        ('Contaduría Pública', 'CP-ELEC2', 3, 'Electiva'),
        ('Contaduría Pública', 'CP-CIF', 4, 'Profesional'),
        ('Contaduría Pública', 'CP-CEF', 4, 'Profesional'),
        ('Contaduría Pública', 'CP-PE', 4, 'Profesional'),
        ('Contaduría Pública', 'CP-IO', 4, 'Profesional'),
        ('Contaduría Pública', 'CP-ELEC3', 4, 'Optativa'),
        ('Contaduría Pública', 'CP-CG', 5, 'Profesional'),
        ('Contaduría Pública', 'CP-CA', 5, 'Profesional'),
        ('Contaduría Pública', 'CP-AF', 5, 'Profesional'),
        ('Contaduría Pública', 'CP-AA', 5, 'Profesional'),
        ('Contaduría Pública', 'CP-MI', 5, 'Profesional'),
        ('Contaduría Pública', 'CP-IRC', 6, 'Profesional'),
        ('Contaduría Pública', 'CP-CFP', 6, 'Profesional'),
        ('Contaduría Pública', 'CP-FNT', 6, 'Profesional'),
        ('Contaduría Pública', 'CP-EP', 6, 'Humanística'),
        ('Contaduría Pública', 'CP-OPT1', 6, 'Optativa'),
        ('Contaduría Pública', 'CP-IVRF', 7, 'Profesional'),
        ('Contaduría Pública', 'CP-RF', 7, 'Profesional'),
        ('Contaduría Pública', 'CP-FC', 7, 'Profesional'),
        ('Contaduría Pública', 'CP-FGP', 7, 'Profesional'),
        ('Contaduría Pública', 'CP-OPT2', 7, 'Optativa'),
        ('Contaduría Pública', 'CP-ITPT', 8, 'Profesional'),
        ('Contaduría Pública', 'CP-AS', 8, 'Profesional'),
        ('Contaduría Pública', 'CP-SG', 8, 'Profesional'),
        ('Contaduría Pública', 'CP-CNG', 8, 'Humanística'),
        ('Contaduría Pública', 'CP-OPT3', 8, 'Optativa'),
        
        # === DERECHO ===
        ('Derecho', 'DER-ID', 1, 'Básica'),
        ('Derecho', 'DER-DR', 1, 'Básica'),
        ('Derecho', 'DER-HD', 1, 'Básica'),
        ('Derecho', 'DER-TE', 1, 'Básica'),
        ('Derecho', 'DER-CC', 1, 'Humanística'),
        ('Derecho', 'DER-CU', 1, 'Humanística'),
        ('Derecho', 'DER-DC1', 2, 'Básica'),
        ('Derecho', 'DER-TGD', 2, 'Básica'),
        ('Derecho', 'DER-DCP', 2, 'Profesional'),
        ('Derecho', 'DER-SJ', 2, 'Humanística'),
        ('Derecho', 'DER-MI', 2, 'Profesional'),
        ('Derecho', 'DER-DC2', 3, 'Básica'),
        ('Derecho', 'DER-DCB', 3, 'Profesional'),
        ('Derecho', 'DER-DPG', 3, 'Profesional'),
        ('Derecho', 'DER-FD', 3, 'Humanística'),
        ('Derecho', 'DER-ELEC1', 3, 'Electiva'),
        ('Derecho', 'DER-DCO', 4, 'Profesional'),
        ('Derecho', 'DER-DPE', 4, 'Profesional'),
        ('Derecho', 'DER-DA1', 4, 'Profesional'),
        ('Derecho', 'DER-HJ', 4, 'Humanística'),
        ('Derecho', 'DER-ELEC2', 4, 'Electiva'),
        ('Derecho', 'DER-DCC', 5, 'Profesional'),
        ('Derecho', 'DER-DPC1', 5, 'Profesional'),
        ('Derecho', 'DER-DA2', 5, 'Profesional'),
        ('Derecho', 'DER-DLI', 5, 'Profesional'),
        ('Derecho', 'DER-ELEC3', 5, 'Electiva'),
        ('Derecho', 'DER-DPC2', 6, 'Profesional'),
        ('Derecho', 'DER-DLC', 6, 'Profesional'),
        ('Derecho', 'DER-DCOM1', 6, 'Profesional'),
        ('Derecho', 'DER-DPP', 6, 'Profesional'),
        ('Derecho', 'DER-EP', 6, 'Humanística'),
        ('Derecho', 'DER-DCOM2', 7, 'Profesional'),
        ('Derecho', 'DER-DPR', 7, 'Profesional'),
        ('Derecho', 'DER-DIP', 7, 'Profesional'),
        ('Derecho', 'DER-DT', 7, 'Profesional'),
        ('Derecho', 'DER-OPT1', 7, 'Optativa'),
        ('Derecho', 'DER-DIPR', 8, 'Profesional'),
        ('Derecho', 'DER-DF', 8, 'Profesional'),
        ('Derecho', 'DER-DPA', 8, 'Profesional'),
        ('Derecho', 'DER-CJ1', 8, 'Práctico'),
        ('Derecho', 'DER-OPT2', 8, 'Optativa'),
        ('Derecho', 'DER-CJ2', 9, 'Práctico'),
        ('Derecho', 'DER-MASC', 9, 'Profesional'),
        ('Derecho', 'DER-SG', 9, 'Profesional'),
        ('Derecho', 'DER-PJ', 10, 'Práctico'),
        ('Derecho', 'DER-OPT3', 10, 'Optativa'),
        
        # === BACTERIOLOGÍA ===
        ('Bacteriología', 'BAC-BIO', 1, 'Básica'),
        ('Bacteriología', 'BAC-QUI', 1, 'Básica'),
        ('Bacteriología', 'BAC-MF1', 1, 'Básica'),
        ('Bacteriología', 'BAC-BF', 1, 'Básica'),
        ('Bacteriología', 'BAC-CC1', 1, 'Humanística'),
        ('Bacteriología', 'BAC-CU', 1, 'Humanística'),
        ('Bacteriología', 'BAC-BQ', 2, 'Básica'),
        ('Bacteriología', 'BAC-MF2', 2, 'Básica'),
        ('Bacteriología', 'BAC-MG', 2, 'Profesional'),
        ('Bacteriología', 'BAC-BEI', 2, 'Básica'),
        ('Bacteriología', 'BAC-EC1', 2, 'Electiva'),
        ('Bacteriología', 'BAC-INM', 3, 'Profesional'),
        ('Bacteriología', 'BAC-PAR', 3, 'Profesional'),
        ('Bacteriología', 'BAC-MIC', 3, 'Profesional'),
        ('Bacteriología', 'BAC-ICE', 3, 'Básica'),
        ('Bacteriología', 'BAC-MI', 3, 'Profesional'),
        ('Bacteriología', 'BAC-BC1', 4, 'Profesional'),
        ('Bacteriología', 'BAC-VIR', 4, 'Profesional'),
        ('Bacteriología', 'BAC-HEM', 4, 'Profesional'),
        ('Bacteriología', 'BAC-SP', 4, 'Profesional'),
        ('Bacteriología', 'BAC-EC2', 4, 'Electiva'),
        ('Bacteriología', 'BAC-MA', 5, 'Profesional'),
        ('Bacteriología', 'BAC-MSA', 5, 'Profesional'),
        ('Bacteriología', 'BAC-IH', 5, 'Profesional'),
        ('Bacteriología', 'BAC-SAO', 5, 'Profesional'),
        ('Bacteriología', 'BAC-EC3', 5, 'Electiva'),
        ('Bacteriología', 'BAC-ADM1', 6, 'Profesional'),
        ('Bacteriología', 'BAC-GC', 6, 'Profesional'),
        ('Bacteriología', 'BAC-INV1', 6, 'Profesional'),
        ('Bacteriología', 'BAC-EGB', 6, 'Humanística'),
        ('Bacteriología', 'BAC-PH1', 7, 'Práctico'),
        ('Bacteriología', 'BAC-EP1', 7, 'Electiva'),
        ('Bacteriología', 'BAC-PH2', 8, 'Práctico'),
        ('Bacteriología', 'BAC-INV2', 8, 'Profesional'),
        ('Bacteriología', 'BAC-PAAL', 9, 'Práctico'),
        ('Bacteriología', 'BAC-PH3', 9, 'Práctico'),
        ('Bacteriología', 'BAC-SPPC', 9, 'Práctico'),
        ('Bacteriología', 'BAC-INV3', 9, 'Profesional'),
        ('Bacteriología', 'BAC-ADM2', 9, 'Profesional'),
        
        # === MICROBIOLOGÍA ===
        ('Microbiología', 'MIC-BIO', 1, 'Básica'),
        ('Microbiología', 'MIC-QUI', 1, 'Básica'),
        ('Microbiología', 'MIC-MF1', 1, 'Básica'),
        ('Microbiología', 'MIC-BF', 1, 'Básica'),
        ('Microbiología', 'MIC-CC1', 1, 'Humanística'),
        ('Microbiología', 'MIC-CU', 1, 'Humanística'),
        ('Microbiología', 'MIC-BQ', 2, 'Básica'),
        ('Microbiología', 'MIC-MF2', 2, 'Básica'),
        ('Microbiología', 'MIC-MG', 2, 'Profesional'),
        ('Microbiología', 'MIC-BEI', 2, 'Básica'),
        ('Microbiología', 'MIC-EC1', 2, 'Electiva'),
        ('Microbiología', 'MIC-INM', 3, 'Profesional'),
        ('Microbiología', 'MIC-PAR', 3, 'Profesional'),
        ('Microbiología', 'MIC-VIR', 3, 'Profesional'),
        ('Microbiología', 'MIC-ICE', 3, 'Básica'),
        ('Microbiología', 'MIC-MI', 3, 'Profesional'),
        ('Microbiología', 'MIC-GM', 4, 'Profesional'),
        ('Microbiología', 'MIC-BC3', 4, 'Profesional'),
        ('Microbiología', 'MIC-MA', 4, 'Profesional'),
        ('Microbiología', 'MIC-FM', 4, 'Profesional'),
        ('Microbiología', 'MIC-EC2', 4, 'Electiva'),
        ('Microbiología', 'MIC-MIND', 5, 'Profesional'),
        ('Microbiología', 'MIC-MM', 5, 'Profesional'),
        ('Microbiología', 'MIC-CT', 5, 'Profesional'),
        ('Microbiología', 'MIC-GC', 5, 'Profesional'),
        ('Microbiología', 'MIC-EC3', 5, 'Electiva'),
        ('Microbiología', 'MIC-ADM1', 6, 'Profesional'),
        ('Microbiología', 'MIC-INV1', 6, 'Profesional'),
        ('Microbiología', 'MIC-EGB', 6, 'Humanística'),
        ('Microbiología', 'MIC-PH1', 7, 'Práctico'),
        ('Microbiología', 'MIC-EP1', 7, 'Electiva'),
        ('Microbiología', 'MIC-PH2', 8, 'Práctico'),
        ('Microbiología', 'MIC-INV2', 8, 'Profesional'),
        ('Microbiología', 'MIC-PAAL', 9, 'Práctico'),
        ('Microbiología', 'MIC-PH3', 9, 'Práctico'),
        ('Microbiología', 'MIC-SPPC', 9, 'Práctico'),
        ('Microbiología', 'MIC-INV3', 9, 'Profesional'),
        ('Microbiología', 'MIC-ADM2', 9, 'Profesional'),
        
        # === FISIOTERAPIA ===
        ('Fisioterapia', 'FIS-BIO', 1, 'Básica'),
        ('Fisioterapia', 'FIS-QUI', 1, 'Básica'),
        ('Fisioterapia', 'FIS-MF1', 1, 'Básica'),
        ('Fisioterapia', 'FIS-BF', 1, 'Básica'),
        ('Fisioterapia', 'FIS-FF', 1, 'Profesional'),
        ('Fisioterapia', 'FIS-CC1', 1, 'Humanística'),
        ('Fisioterapia', 'FIS-CU', 1, 'Humanística'),
        ('Fisioterapia', 'FIS-BQ', 2, 'Básica'),
        ('Fisioterapia', 'FIS-MF2', 2, 'Básica'),
        ('Fisioterapia', 'FIS-KIN', 2, 'Profesional'),
        ('Fisioterapia', 'FIS-BEI', 2, 'Básica'),
        ('Fisioterapia', 'FIS-EC1', 2, 'Electiva'),
        ('Fisioterapia', 'FIS-MF3', 3, 'Básica'),
        ('Fisioterapia', 'FIS-CIN', 3, 'Profesional'),
        ('Fisioterapia', 'FIS-MAS', 3, 'Profesional'),
        ('Fisioterapia', 'FIS-MEC', 3, 'Profesional'),
        ('Fisioterapia', 'FIS-ICE', 3, 'Básica'),
        ('Fisioterapia', 'FIS-MI', 3, 'Profesional'),
        ('Fisioterapia', 'FIS-FPE', 4, 'Profesional'),
        ('Fisioterapia', 'FIS-ELE', 4, 'Profesional'),
        ('Fisioterapia', 'FIS-FCP', 4, 'Profesional'),
        ('Fisioterapia', 'FIS-HID', 4, 'Profesional'),
        ('Fisioterapia', 'FIS-CN', 4, 'Humanística'),
        ('Fisioterapia', 'FIS-EC2', 4, 'Electiva'),
        ('Fisioterapia', 'FIS-FNE', 5, 'Profesional'),
        ('Fisioterapia', 'FIS-FOT', 5, 'Profesional'),
        ('Fisioterapia', 'FIS-FGE', 5, 'Profesional'),
        ('Fisioterapia', 'FIS-AT', 5, 'Profesional'),
        ('Fisioterapia', 'FIS-SST', 5, 'Profesional'),
        ('Fisioterapia', 'FIS-EC3', 5, 'Electiva'),
        ('Fisioterapia', 'FIS-ADM1', 6, 'Profesional'),
        ('Fisioterapia', 'FIS-CSS', 6, 'Profesional'),
        ('Fisioterapia', 'FIS-INV1', 6, 'Profesional'),
        ('Fisioterapia', 'FIS-EGDF', 6, 'Humanística'),
        ('Fisioterapia', 'FIS-PH1', 7, 'Práctico'),
        ('Fisioterapia', 'FIS-EP1', 7, 'Electiva'),
        ('Fisioterapia', 'FIS-PH2', 8, 'Práctico'),
        ('Fisioterapia', 'FIS-FMO', 8, 'Profesional'),
        ('Fisioterapia', 'FIS-INV2', 8, 'Profesional'),
        ('Fisioterapia', 'FIS-ADM2', 8, 'Profesional'),
        ('Fisioterapia', 'FIS-PH3', 9, 'Práctico'),
        ('Fisioterapia', 'FIS-PAADM', 9, 'Práctico'),
        ('Fisioterapia', 'FIS-SPPC', 9, 'Práctico'),
        ('Fisioterapia', 'FIS-INV3', 9, 'Profesional'),
        
        # === INSTRUMENTACIÓN QUIRÚRGICA ===
        ('Instrumentación Quirúrgica', 'IQ-BIO', 1, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-QUI', 1, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-MF1', 1, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-BF', 1, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-IIQ', 1, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-CC1', 1, 'Humanística'),
        ('Instrumentación Quirúrgica', 'IQ-CU', 1, 'Humanística'),
        ('Instrumentación Quirúrgica', 'IQ-BQ', 2, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-MF2', 2, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-MIC', 2, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-PA1', 2, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-BEI', 2, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-EC1', 2, 'Electiva'),
        ('Instrumentación Quirúrgica', 'IQ-FA', 3, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-CIPS', 3, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-PQCGP', 3, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-ICE', 3, 'Básica'),
        ('Instrumentación Quirúrgica', 'IQ-MI', 3, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-PQGO', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-PQU', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-PA2', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-CN', 4, 'Humanística'),
        ('Instrumentación Quirúrgica', 'IQ-SST', 4, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-EC2', 4, 'Electiva'),
        ('Instrumentación Quirúrgica', 'IQ-PQO', 5, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-PQN', 5, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-IT', 5, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-GC', 5, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-EC3', 5, 'Electiva'),
        ('Instrumentación Quirúrgica', 'IQ-ADM1', 6, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-CSS', 6, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-INV1', 6, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-EGDIQ', 6, 'Humanística'),
        ('Instrumentación Quirúrgica', 'IQ-PH1', 7, 'Práctico'),
        ('Instrumentación Quirúrgica', 'IQ-EP1', 7, 'Electiva'),
        ('Instrumentación Quirúrgica', 'IQ-PH2', 8, 'Práctico'),
        ('Instrumentación Quirúrgica', 'IQ-PQCM', 8, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-INV2', 8, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-ADM2', 8, 'Profesional'),
        ('Instrumentación Quirúrgica', 'IQ-PH3', 9, 'Práctico'),
        ('Instrumentación Quirúrgica', 'IQ-PAADM', 9, 'Práctico'),
        ('Instrumentación Quirúrgica', 'IQ-SPPC', 9, 'Práctico'),
        ('Instrumentación Quirúrgica', 'IQ-INV3', 9, 'Profesional'),
        
        # === MEDICINA ===
        ('Medicina', 'MED-BCM', 1, 'Básica'),
        ('Medicina', 'MED-QUI', 1, 'Básica'),
        ('Medicina', 'MED-MORF1', 1, 'Básica'),
        ('Medicina', 'MED-CC1', 1, 'Humanística'),
        ('Medicina', 'MED-AMA', 1, 'Humanística'),
        ('Medicina', 'MED-PS1', 1, 'Práctico'),
        ('Medicina', 'MED-CU', 1, 'Humanística'),
        ('Medicina', 'MED-BQ', 2, 'Básica'),
        ('Medicina', 'MED-MORF2', 2, 'Básica'),
        ('Medicina', 'MED-FIS1', 2, 'Básica'),
        ('Medicina', 'MED-CC2', 2, 'Humanística'),
        ('Medicina', 'MED-BEI', 2, 'Básica'),
        ('Medicina', 'MED-PS2', 2, 'Práctico'),
        ('Medicina', 'MED-FIS2', 3, 'Básica'),
        ('Medicina', 'MED-MP', 3, 'Básica'),
        ('Medicina', 'MED-GEN', 3, 'Básica'),
        ('Medicina', 'MED-FPS', 3, 'Humanística'),
        ('Medicina', 'MED-EGB', 3, 'Humanística'),
        ('Medicina', 'MED-PS3', 3, 'Práctico'),
        ('Medicina', 'MED-INM', 4, 'Básica'),
        ('Medicina', 'MED-SEM1', 4, 'Profesional'),
        ('Medicina', 'MED-PAT1', 4, 'Básica'),
        ('Medicina', 'MED-NUT', 4, 'Básica'),
        ('Medicina', 'MED-EPI1', 4, 'Básica'),
        ('Medicina', 'MED-SA', 4, 'Humanística'),
        ('Medicina', 'MED-SEM2', 5, 'Profesional'),
        ('Medicina', 'MED-PAT2', 5, 'Básica'),
        ('Medicina', 'MED-FARM1', 5, 'Básica'),
        ('Medicina', 'MED-MP2', 5, 'Profesional'),
        ('Medicina', 'MED-EC1', 5, 'Electiva'),
        ('Medicina', 'MED-MI1', 6, 'Profesional'),
        ('Medicina', 'MED-CIR1', 6, 'Profesional'),
        ('Medicina', 'MED-FARM2', 6, 'Básica'),
        ('Medicina', 'MED-MINV', 6, 'Profesional'),
        ('Medicina', 'MED-CN', 6, 'Humanística'),
        ('Medicina', 'MED-MI2', 7, 'Profesional'),
        ('Medicina', 'MED-CIR2', 7, 'Profesional'),
        ('Medicina', 'MED-PED1', 7, 'Profesional'),
        ('Medicina', 'MED-GO1', 7, 'Profesional'),
        ('Medicina', 'MED-EPI2', 7, 'Básica'),
        ('Medicina', 'MED-MI3', 8, 'Profesional'),
        ('Medicina', 'MED-CIR3', 8, 'Profesional'),
        ('Medicina', 'MED-PED2', 8, 'Profesional'),
        ('Medicina', 'MED-GO2', 8, 'Profesional'),
        ('Medicina', 'MED-INV1', 8, 'Profesional'),
        ('Medicina', 'MED-PSI', 9, 'Profesional'),
        ('Medicina', 'MED-ORT', 9, 'Profesional'),
        ('Medicina', 'MED-URO', 9, 'Profesional'),
        ('Medicina', 'MED-OFT', 9, 'Profesional'),
        ('Medicina', 'MED-ORL', 9, 'Profesional'),
        ('Medicina', 'MED-INV2', 9, 'Profesional'),
        ('Medicina', 'MED-ML', 10, 'Profesional'),
        ('Medicina', 'MED-DER', 10, 'Profesional'),
        ('Medicina', 'MED-ANE', 10, 'Profesional'),
        ('Medicina', 'MED-RAD', 10, 'Profesional'),
        ('Medicina', 'MED-EP1', 10, 'Electiva'),
        ('Medicina', 'MED-INV3', 10, 'Profesional'),
        ('Medicina', 'MED-IR', 11, 'Práctico'),
    ]
    
    created_count = 0
    skipped_count = 0
    
    for nombre_programa, codigo_asignatura, semestre, componente in relaciones_data:
        try:
            programa = Programa.objects.get(nombre=nombre_programa)
            asignatura = Asignatura.objects.get(codigo=codigo_asignatura)
            
            _, created = AsignaturaPrograma.objects.get_or_create(
                programa=programa,
                asignatura=asignatura,
                defaults={
                    'semestre': semestre,
                    'componente_formativo': componentes_map.get(componente, 'Básica')
                }
            )
            if created:
                created_count += 1
        except Programa.DoesNotExist:
            stdout.write(style.WARNING(f'    ! Programa no encontrado: {nombre_programa}'))
            skipped_count += 1
        except Asignatura.DoesNotExist:
            stdout.write(style.WARNING(f'    ! Asignatura no encontrada: {codigo_asignatura}'))
            skipped_count += 1
    
    total = len(relaciones_data)
    stdout.write(style.SUCCESS(f'    ✓ Relaciones procesadas: {created_count} nuevas, {skipped_count} omitidas, {total} totales'))

