# Generated by Django 4.2.26 on 2025-11-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('espacios', '0001_initial'),
        ('grupos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFusionado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_estudiantes', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados', to='asignaturas.asignatura')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_fusionados', to='usuarios.usuario')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados', to='espacios.espaciofisico')),
                ('grupo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados_1', to='grupos.grupo')),
                ('grupo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados_2', to='grupos.grupo')),
                ('grupo3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados_3', to='grupos.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_estudiantes', models.IntegerField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='asignaturas.asignatura')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_docente', to='usuarios.usuario')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='espacios.espaciofisico')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='grupos.grupo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='horariofusionado',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_horario_fusionado_horas'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['espacio'], name='idx_horario_espacio'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['docente'], name='idx_horario_docente'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_horario_horas'),
        ),
    ]
