# Generated by Django
from django.db import migrations
import datetime

def crear_horarios_prueba(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    Horario = apps.get_model('horario', 'Horario')
    Grupo = apps.get_model('grupos', 'Grupo')
    Asignatura = apps.get_model('asignaturas', 'Asignatura')
    EspacioFisico = apps.get_model('espacios', 'EspacioFisico')
    
    # Buscar docente por email
    try:
        docente = Usuario.objects.get(correo='docente@unilibre.edu.co')
    except Usuario.DoesNotExist:
        print("Usuario docente@unilibre.edu.co no encontrado. Saltando creación de horarios.")
        return
    
    # Obtener datos necesarios
    grupo = Grupo.objects.first()
    asignaturas = list(Asignatura.objects.all()[:3])
    espacios = list(EspacioFisico.objects.all()[:2])
    
    # Si no hay datos, salir sin error
    if not grupo or len(asignaturas) < 3 or len(espacios) < 2:
        print("No hay suficientes datos (grupos/asignaturas/espacios). Saltando creación de horarios.")
        return
    
    # Eliminar horarios existentes del docente
    Horario.objects.filter(docente=docente).delete()
    
    # Crear horarios de prueba
    horarios_prueba = [
        # Lunes
        {
            'grupo': grupo,
            'asignatura': asignaturas[0],
            'docente': docente,
            'espacio': espacios[0],
            'dia_semana': 'Lunes',
            'hora_inicio': datetime.time(8, 0),
            'hora_fin': datetime.time(10, 0),
            'cantidad_estudiantes': 30
        },
        {
            'grupo': grupo,
            'asignatura': asignaturas[1],
            'docente': docente,
            'espacio': espacios[1],
            'dia_semana': 'Lunes',
            'hora_inicio': datetime.time(14, 0),
            'hora_fin': datetime.time(16, 0),
            'cantidad_estudiantes': 25
        },
        # Martes
        {
            'grupo': grupo,
            'asignatura': asignaturas[0],
            'docente': docente,
            'espacio': espacios[0],
            'dia_semana': 'Martes',
            'hora_inicio': datetime.time(10, 0),
            'hora_fin': datetime.time(12, 0),
            'cantidad_estudiantes': 30
        },
        # Miércoles
        {
            'grupo': grupo,
            'asignatura': asignaturas[1],
            'docente': docente,
            'espacio': espacios[1],
            'dia_semana': 'Miércoles',
            'hora_inicio': datetime.time(8, 0),
            'hora_fin': datetime.time(10, 0),
            'cantidad_estudiantes': 25
        },
        {
            'grupo': grupo,
            'asignatura': asignaturas[2],
            'docente': docente,
            'espacio': espacios[0],
            'dia_semana': 'Miércoles',
            'hora_inicio': datetime.time(16, 0),
            'hora_fin': datetime.time(18, 0),
            'cantidad_estudiantes': 20
        },
        # Jueves
        {
            'grupo': grupo,
            'asignatura': asignaturas[2],
            'docente': docente,
            'espacio': espacios[1],
            'dia_semana': 'Jueves',
            'hora_inicio': datetime.time(14, 0),
            'hora_fin': datetime.time(16, 0),
            'cantidad_estudiantes': 20
        },
        # Viernes
        {
            'grupo': grupo,
            'asignatura': asignaturas[0],
            'docente': docente,
            'espacio': espacios[0],
            'dia_semana': 'Viernes',
            'hora_inicio': datetime.time(9, 0),
            'hora_fin': datetime.time(11, 0),
            'cantidad_estudiantes': 30
        },
    ]
    
    # Crear los horarios
    for horario_data in horarios_prueba:
        Horario.objects.create(**horario_data)
    
    print(f"✅ Se crearon {len(horarios_prueba)} horarios de prueba para {docente.nombre} ({docente.correo})")

def eliminar_horarios_prueba(apps, schema_editor):
    """Revertir la migración eliminando los horarios creados"""
    Horario = apps.get_model('horario', 'Horario')
    Usuario = apps.get_model('usuarios', 'Usuario')
    
    try:
        docente = Usuario.objects.get(correo='docente@unilibre.edu.co')
        Horario.objects.filter(docente=docente).delete()
    except Usuario.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
        ('asignaturas', '0006_remove_asignatura_programa'),
    ]

    operations = [
        migrations.RunPython(crear_horarios_prueba, eliminar_horarios_prueba),
    ]
