# Generated by Django 4.2.26 on 2025-11-30 16:00

from django.db import migrations, models
import django.db.models.deletion

def seed_horario_estudiante(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    Horario = apps.get_model('horario', 'Horario')
    HorarioEstudiante = apps.get_model('horario', 'HorarioEstudiante')

    try:
        estudiante = Usuario.objects.get(correo='estudiante@unilibre.edu.co')
    except Usuario.DoesNotExist:
        print("Usuario estudiante@unilibre.edu.co no encontrado. Saltando seed.")
        return

    horarios = list(Horario.objects.all()[:3])
    if not horarios:
        print("No hay horarios para inscribir.")
        return

    for h in horarios:
        HorarioEstudiante.objects.get_or_create(estudiante=estudiante, horario=h)
    
    print(f"✅ Estudiante {estudiante.nombre} inscrito en {len(horarios)} horarios.")

def reverse_seed(apps, schema_editor):
    HorarioEstudiante = apps.get_model('horario', 'HorarioEstudiante')
    Usuario = apps.get_model('usuarios', 'Usuario')
    try:
        estudiante = Usuario.objects.get(correo='estudiante@unilibre.edu.co')
        HorarioEstudiante.objects.filter(estudiante=estudiante).delete()
    except Usuario.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('horario', '0002_seed_horarios_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEstudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_inscritos', to='horario.horario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_inscritos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Horario de Estudiante',
                'verbose_name_plural': 'Horarios de Estudiantes',
                'unique_together': {('horario', 'estudiante')},
            },
        ),
        migrations.RunPython(seed_horario_estudiante, reverse_seed),
    ]
