# Generated by Django 5.2.7 on 2026-05-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0007_stgoracleespaciofisico'),
        ('horario', '0006_stgoraclehorario_num_dia_oracle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='espacios.espaciofisico'),
        ),
    ]
