# Generated by Django 5.2.15 on 2026-08-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0007_alter_horario_espacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='origen',
            field=models.CharField(choices=[('SIUL', 'SIUL'), ('SIHUL', 'SIHUL')], default='SIHUL', max_length=10),
        ),
    ]
