# Generated by Django 5.2.15 on 2026-08-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0008_horario_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='oracle_external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
