# Generated by Django 4.2.26 on 2025-11-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioFisico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('recursos', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='sedes.sede')),
            ],
        ),
    ]
