# Generated by Django 4.2.26 on 2025-11-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaciorecurso',
            name='disponible',
        ),
        migrations.AddField(
            model_name='espaciorecurso',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible'), ('en_mantenimiento', 'En Mantenimiento')], default='disponible', max_length=50),
        ),
    ]
