# Generated by Django - Data Migration

from django.db import migrations

def create_default_recursos(apps, schema_editor):
    """
    Crea recursos por defecto para los espacios físicos
    """
    Recurso = apps.get_model('recursos', 'Recurso')
    
    recursos_default = [
        {'nombre': 'Proyector', 'descripcion': 'Proyector multimedia para presentaciones'},
        {'nombre': 'Micrófono', 'descripcion': 'Micrófono inalámbrico'},
        {'nombre': 'Sonido', 'descripcion': 'Sistema de sonido profesional'},
        {'nombre': 'Computadores', 'descripcion': 'Computadores de escritorio para estudiantes'},
        {'nombre': 'Videoconferencia', 'descripcion': 'Sistema de videoconferencia'},
        {'nombre': 'Pizarra Digital', 'descripcion': 'Pizarra digital interactiva'},
        {'nombre': 'Aire Acondicionado', 'descripcion': 'Sistema de climatización'},
        {'nombre': 'Sillas Adicionales', 'descripcion': 'Sillas adicionales móviles'},
        {'nombre': 'Mesas', 'descripcion': 'Mesas de trabajo'},
        {'nombre': 'Atril', 'descripcion': 'Atril para presentaciones'},
        {'nombre': 'Pantalla Extra', 'descripcion': 'Pantalla adicional para proyección'},
        {'nombre': 'Internet', 'descripcion': 'Conexión a internet de alta velocidad'},
        {'nombre': 'Tablero', 'descripcion': 'Tablero acrílico para marcadores'},
        {'nombre': 'Marcadores', 'descripcion': 'Set de marcadores borrables'},
        {'nombre': 'Borrador', 'descripcion': 'Borrador para tablero'},
    ]
    
    for recurso_data in recursos_default:
        # Verificar si el recurso ya existe
        if not Recurso.objects.filter(nombre=recurso_data['nombre']).exists():
            Recurso.objects.create(**recurso_data)
            print(f"✅ Creado recurso: {recurso_data['nombre']}")
        else:
            print(f"⚠️ Recurso ya existe: {recurso_data['nombre']}")

def reverse_recursos(apps, schema_editor):
    """
    Elimina los recursos por defecto si se revierte la migración
    """
    Recurso = apps.get_model('recursos', 'Recurso')
    
    nombres_recursos = [
        'Proyector', 'Micrófono', 'Sonido', 'Computadores', 
        'Videoconferencia', 'Pizarra Digital', 'Aire Acondicionado',
        'Sillas Adicionales', 'Mesas', 'Atril', 'Pantalla Extra',
        'Internet', 'Tablero', 'Marcadores', 'Borrador'
    ]
    
    Recurso.objects.filter(nombre__in=nombres_recursos).delete()
    print("🗑️ Recursos por defecto eliminados")

class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_remove_espaciorecurso_disponible_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_recursos, reverse_recursos),
    ]
