export * from './users/user.model';
export * from './academica/academica.model';
export type { RecursoConEstado, EspacioFisico, EquipamientoEspacio } from './espacios/espacio.model';
export * from './recursos/recurso.model';
export * from './shared/shared.model';
export * from './dashboard/stats.model';
export * from './users/notification.model';
export * from './horarios/horario.model';
export * from './horarios/visualizacion.model';
export * from './reporte/ocupacion.model';
export * from './reporte/reportes.model';
export * from './reporte/reportes-general.model';
export * from './espacios/espacios.model';
export * from './espacios/prestamos-espacios.model';
export * from './espacios/supervisor.model';
export * from './prestamos/prestamo.model';
