# Generated by Django 4.2.26 on 2025-11-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='tipo',
            field=models.CharField(choices=[('teórica', 'Teórica'), ('práctica', 'Práctica'), ('mixta', 'Mixta')], default='presencial', max_length=20),
        ),
    ]
