# Generated by Django 4.2.26 on 2025-11-29 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facultades', '0001_initial'),
        ('asignaturas', '0002_asignatura_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='facultades.facultad'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
