# Generated by Django 4.2.26 on 2025-11-29 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_programa_semestres'),
        ('asignaturas', '0003_asignatura_facultad_asignatura_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='facultad',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='programas.programa'),
        ),
    ]
