# Generated by Django 4.2.26 on 2025-11-29 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_programa_semestres'),
        ('asignaturas', '0004_remove_asignatura_facultad_asignatura_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaPrograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.PositiveIntegerField()),
                ('componente_formativo', models.CharField(choices=[('electiva', 'Electiva'), ('optativa', 'Optativa'), ('profesional', 'Profesional'), ('humanística', 'Humanística'), ('básica', 'Básica')], default='profesional', max_length=20)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_asignatura', to='asignaturas.asignatura')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_programa', to='programas.programa')),
            ],
            options={
                'verbose_name': 'Asignatura por Programa',
                'verbose_name_plural': 'Asignaturas por Programa',
                'unique_together': {('programa', 'asignatura', 'semestre')},
            },
        ),
    ]
