# Generated by Django 4.2.26 on 2025-11-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0005_asignaturaprograma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignaturaprograma',
            old_name='tipo',
            new_name='componente_formativo',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='programa',
        ),
    ]
