# Generated by Django 4.2.26 on 2025-11-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0005_asignaturaprograma'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='asignatura',
                    name='programa',
                ),
            ],
            database_operations=[
                # No operation because the column is already missing in the DB
            ],
        ),
    ]
