# Generated by Django 5.2.7 on 2026-04-02 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0006_remove_asignatura_programa'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_sede', to='sedes.sede'),
        ),
    ]
