# Generated by Django 4.2.26 on 2025-11-30 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='Bot', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('bg_gradient', models.CharField(default='from-blue-500 via-blue-600 to-indigo-600', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('mensaje_bienvenida', models.TextField()),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaSugerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('contador_uso', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='chatbot.agente')),
            ],
            options={
                'verbose_name': 'Pregunta Sugerida',
                'verbose_name_plural': 'Preguntas Sugeridas',
                'ordering': ['agente', 'orden'],
            },
        ),
    ]
