# Generated by Django 5.2.7-alpha
from django.db import migrations

def seed_agente_biblioteca(apps, schema_editor):
    Agente = apps.get_model('chatbot', 'Agente')
    PreguntaSugerida = apps.get_model('chatbot', 'PreguntaSugerida')
    
    # Crear Agente de Biblioteca
    biblioteca = Agente.objects.create(
        nombre='Agente Biblioteca',
        subtitulo='Asistente de Biblioteca',
        descripcion='Consultas sobre préstamos de libros, horarios de la biblioteca, reservas de salas de estudio y recursos bibliográficos.',
        icono='BookOpen',
        color='blue',
        bg_gradient='from-blue-500 via-blue-600 to-indigo-600',
        activo=True,
        endpoint_url='https://unilibrerag.app.n8n.cloud/webhook/409ecf49-cd44-4b01-ac40-4cda200d96e8',
        mensaje_bienvenida='¡Hola! 👋 Soy tu asistente de biblioteca.\n\nPuedo ayudarte con:\n📚 Préstamos de libros\n⏰ Horarios de la biblioteca\n📖 Reservas de salas de estudio\n🔄 Renovaciones\n\n¿En qué puedo asistirte hoy?',
        orden=1
    )
    
    # Crear preguntas sugeridas basadas en el contexto de la Universidad Libre
    preguntas = [
        '¿Qué horarios tiene la biblioteca?',
        '¿Cómo puedo renovar un libro?',
        '¿Cuántas renovaciones puedo hacer?',
        '¿Cómo reservo una sala de estudio?',
        '¿Cuál es el tiempo de préstamo para estudiantes de pregrado?',
        '¿Cómo puedo subir mi trabajo de grado al repositorio?',
        '¿Qué función tiene la cuenta de usuario de la biblioteca?',
        '¿Cuál es el correo para consultas sobre el repositorio?',
        '¿Qué es la Universidad Libre?',
        '¿Cuál es la línea gratuita de la Universidad Libre?'
    ]
    
    for idx, pregunta in enumerate(preguntas, start=1):
        PreguntaSugerida.objects.create(
            agente=biblioteca,
            pregunta=pregunta,
            orden=idx,
            contador_uso=0,
            activo=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_agente_biblioteca),
    ]
