# Generated by Django
from django.db import migrations

def update_questions(apps, schema_editor):
    Agente = apps.get_model('chatbot', 'Agente')
    PreguntaSugerida = apps.get_model('chatbot', 'PreguntaSugerida')
    
    try:
        biblioteca = Agente.objects.get(nombre='Agente Biblioteca')
        
        # Eliminar preguntas existentes para evitar duplicados y limpiar
        PreguntaSugerida.objects.filter(agente=biblioteca).delete()
        
        nuevas_preguntas = [
            "¿Qué función principal permite realizar la cuenta de usuario de la Biblioteca?",
            "¿Cuántas renovaciones se permiten para Libros de Colección General a estudiantes?",
            "¿Cuántas renovaciones se permiten para Libros de Colección General a docentes?",
            "¿A qué usuarios no aplica la renovación de Libros de Colección General?",
            "¿Cuál es el tiempo de renovación para material de Literatura?",
            "¿Por cuánto tiempo se prestan los libros de Colección Reserva?",
            "¿Qué tipo de uso tienen las Revistas y libros de Referencia?",
            "¿Cuál es el horario de atención de la Biblioteca en Sede Principal?",
            "¿Cuál es el horario de atención de la Biblioteca en Sede Centro?",
            "¿Cuál es el número de teléfono de Circulación y préstamo?",
            "¿Cuál es el correo para consultas sobre el Repositorio Institucional?",
            "¿Cuál es la línea gratuita nacional de la Universidad Libre?",
            "¿Cuáles son los recursos de información virtuales disponibles?",
            "¿Qué servicios específicos ofrece la biblioteca?",
            "¿Qué actividad cultural realiza la Biblioteca una vez al año?",
            "¿Con qué frecuencia se organiza la Feria de Servicios?",
            "¿Qué tecnología usa la biblioteca para mejorar la experiencia?",
            "¿Qué se debe hacer para pagar en línea (PSE) un servicio?",
            "¿Qué herramientas de apoyo a la investigación existen?",
            "¿Qué es el servicio de autoarchivo en el Repositorio Institucional?",
            "¿Qué deben autorizar los autores para el Repositorio Institucional?",
            "¿A qué correo escribir dudas sobre carga en el Repositorio?",
            "¿Qué hacer si el trabajo de grado tiene anexos que no son PDF?",
            "¿Se puede cargar un artículo como requisito de grado?",
            "¿Cómo se notifica la aprobación del trabajo de grado?",
            "¿Cuál es el tiempo de validación en el Repositorio?",
            "¿A quién está dirigido el préstamo de portátiles?",
            "¿Cuál es la duración del préstamo de portátiles?",
            "¿Cuáles son los requisitos para préstamo de portátiles?",
            "¿Cuál es el tiempo de préstamo para libros de Colección General?",
            "¿Cómo funciona el préstamo interbibliotecario?",
            "¿Cómo funciona el préstamo externo Luis Ángel Arango?",
            "¿Quién diligencia el formato de solicitud de material?",
            "¿A quién se envía la solicitud de material desde decanatura?",
            "¿Qué permite el servicio de Asesoría y Formación?",
            "¿Cuál es el correo para donaciones bibliográficas?"
        ]
        
        for idx, pregunta in enumerate(nuevas_preguntas, start=1):
            PreguntaSugerida.objects.create(
                agente=biblioteca,
                pregunta=pregunta,
                orden=idx,
                contador_uso=0,
                activo=True
            )
            
        print(f"✅ Se actualizaron {len(nuevas_preguntas)} preguntas sugeridas para el Agente Biblioteca")
            
    except Agente.DoesNotExist:
        print("Agente Biblioteca no encontrado. Saltando actualización.")

class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_seed_biblioteca'),
    ]

    operations = [
        migrations.RunPython(update_questions),
    ]
