# Generated by Django 5.2.7 on 2025-12-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_conversacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversacion',
            new_name='chatbot_con_chat_id_75d75e_idx',
            old_name='chatbot_con_chat_id_idx',
        ),
        migrations.RenameIndex(
            model_name='conversacion',
            new_name='chatbot_con_chatbot_a451da_idx',
            old_name='chatbot_con_chatbot_idx',
        ),
        migrations.RenameIndex(
            model_name='conversacion',
            new_name='chatbot_con_id_usua_c6ccc3_idx',
            old_name='chatbot_con_usuario_idx',
        ),
    ]
