# Generated by Django 5.2.16 on 2026-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_rename_chatbot_con_chat_id_idx_chatbot_con_chat_id_75d75e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sede', models.CharField(db_index=True, max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Mensaje del Chatbot App',
                'verbose_name_plural': 'Mensajes del Chatbot App',
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatbotChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sede', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Fragmento del Chatbot',
                'verbose_name_plural': 'Fragmentos del Chatbot',
                'db_table': 'chunks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatbotDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sede', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Documento del Chatbot',
                'verbose_name_plural': 'Documentos del Chatbot',
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
