# Generated by Django 5.2.16 on 2026-10-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_sync_rag_unmanaged_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='instrucciones_adicionales',
            field=models.TextField(blank=True, default='', help_text='Ajustes finos de comportamiento que se añaden al perfil del tipo (p. ej. "responde siempre en inglés"). No pueden anular la regla de responder solo con los documentos cargados.', max_length=2000),
        ),
        migrations.AddField(
            model_name='agente',
            name='tipo',
            field=models.CharField(choices=[('normativo', 'Normativo (reglamentos, manuales, procedimientos)'), ('investigativo', 'Investigativo (monografías, tesis, artículos)')], default='normativo', max_length=20),
        ),
    ]
