# Generated by Django 4.2.26 on 2025-11-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoEspacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_admin', to='usuarios.usuario')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='espacios.espaciofisico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_solicitados', to='usuarios.usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['espacio', 'fecha'], name='idx_prestamo_espacio_fecha')],
            },
        ),
        migrations.AddConstraint(
            model_name='prestamoespacio',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_prestamo_horas'),
        ),
    ]
