# Generated by Django 4.2.26 on 2025-11-30 02:15

from django.db import migrations, models
import django.db.models.deletion


def create_default_tipo_actividad(apps, schema_editor):
    """Crear el tipo de actividad por defecto antes de agregar el campo FK"""
    TipoActividad = apps.get_model('prestamos', 'TipoActividad')
    if not TipoActividad.objects.filter(id=1).exists():
        TipoActividad.objects.create(
            id=1,
            nombre='Otro',
            descripcion='Otras actividades academicas'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_remove_espaciorecurso_disponible_and_more'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        # Paso 1: Crear el modelo TipoActividad
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'ordering': ['nombre'],
            },
        ),
        # Paso 2: Crear el registro por defecto con id=1
        migrations.RunPython(create_default_tipo_actividad, migrations.RunPython.noop),
        # Paso 3: Agregar el campo con el default que ahora existe
        migrations.AddField(
            model_name='prestamoespacio',
            name='tipo_actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='prestamos.tipoactividad'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PrestamoRecurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_recursos', to='prestamos.prestamoespacio')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='recursos.recurso')),
            ],
            options={
                'verbose_name': 'Recurso de Préstamo',
                'verbose_name_plural': 'Recursos de Préstamos',
                'unique_together': {('prestamo', 'recurso')},
            },
        ),
    ]
