# Generated by Django 4.2.26 on 2025-11-30 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_load_default_recursos'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='tipo_actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='prestamos.tipoactividad'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PrestamoRecurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_recursos', to='prestamos.prestamoespacio')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='recursos.recurso')),
            ],
            options={
                'verbose_name': 'Recurso de Préstamo',
                'verbose_name_plural': 'Recursos de Préstamos',
                'unique_together': {('prestamo', 'recurso')},
            },
        ),
    ]
