# Generated by Django 5.1.3 on 2025-11-30 02:24

from django.db import migrations

def seed_tipos_actividad(apps, schema_editor):
    TipoActividad = apps.get_model('prestamos', 'TipoActividad')
    db_alias = schema_editor.connection.alias
    
    tipos = [
        ('Clase Adicional', 'Clase fuera del horario habitual'),
        ('Tutoria Grupal', 'Sesion de tutoria para grupos'),
        ('Conferencia', 'Evento tipo conferencia o charla'),
        ('Taller', 'Actividad practica o taller'),
        ('Reunion Academica', 'Reunion de docentes o area'),
        ('Asesoria de Proyecto', 'Asesoria para proyectos de grado o investigacion'),
        ('Examen Especial', 'Examen de validacion o supletorio'),
        ('Evento Cultural', 'Actividad cultural o artistica'),
        ('Otro', 'Otras actividades academicas')  # Siempre debe ser el último
    ]
    
    # Si ya existen tipos, no hacer nada (migración ya ejecutada)
    if TipoActividad.objects.using(db_alias).exists():
        return
    
    # Crear los tipos en el orden definido
    for nombre, descripcion in tipos:
        try:
            TipoActividad.objects.using(db_alias).create(
                nombre=nombre,
                descripcion=descripcion
            )
        except Exception as e:
            # Si falla, continuar con el siguiente
            print(f"Warning: No se pudo crear TipoActividad '{nombre}': {e}")
            continue
    
    # Resetear la secuencia de PostgreSQL
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT setval(pg_get_serial_sequence('prestamos_tipoactividad', 'id'), "
                "(SELECT MAX(id) FROM prestamos_tipoactividad), true);"
            )

def reverse_seed(apps, schema_editor):
    TipoActividad = apps.get_model('prestamos', 'TipoActividad')
    TipoActividad.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_tipoactividad_prestamoespacio_tipo_actividad_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_tipos_actividad, reverse_seed),
    ]
