# Generated by Django 5.1.3 on 2025-11-30 02:24

from django.db import migrations

def seed_tipos_actividad(apps, schema_editor):
    TipoActividad = apps.get_model('prestamos', 'TipoActividad')
    
    tipos = [
        ('Clase Adicional', 'Clase fuera del horario habitual'),
        ('Tutoria Grupal', 'Sesion de tutoria para grupos'),
        ('Conferencia', 'Evento tipo conferencia o charla'),
        ('Taller', 'Actividad practica o taller'),
        ('Reunion Academica', 'Reunion de docentes o area'),
        ('Asesoria de Proyecto', 'Asesoria para proyectos de grado o investigacion'),
        ('Examen Especial', 'Examen de validacion o supletorio'),
        ('Evento Cultural', 'Actividad cultural o artistica'),
        ('Otro', 'Otras actividades academicas')
    ]
    
    for nombre, descripcion in tipos:
        if not TipoActividad.objects.filter(nombre=nombre).exists():
            TipoActividad.objects.create(nombre=nombre, descripcion=descripcion)

def reverse_seed(apps, schema_editor):
    TipoActividad = apps.get_model('prestamos', 'TipoActividad')
    TipoActividad.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_tipoactividad_prestamoespacio_tipo_actividad_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_tipos_actividad, reverse_seed),
    ]
