# Generated by Django 5.2.7 on 2025-12-05 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0005_tipoespacio_alter_espaciofisico_tipo'),
        ('prestamos', '0004_add_asistentes_telefono'),
        ('usuarios', '0004_usuario_sede_usuario_idx_usuario_sede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamoespacio',
            options={'verbose_name': 'Préstamo de Espacio', 'verbose_name_plural': 'Préstamos de Espacios'},
        ),
        migrations.CreateModel(
            name='PrestamoEspacioPublico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_solicitante', models.CharField(max_length=200)),
                ('correo_solicitante', models.EmailField(max_length=254)),
                ('telefono_solicitante', models.CharField(max_length=20)),
                ('identificacion_solicitante', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('asistentes', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_publicos_admin', to='usuarios.usuario')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_publicos', to='espacios.espaciofisico')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_publicos', to='prestamos.tipoactividad')),
            ],
            options={
                'verbose_name': 'Préstamo Público de Espacio',
                'verbose_name_plural': 'Préstamos Públicos de Espacios',
                'indexes': [models.Index(fields=['espacio', 'fecha'], name='idx_pub_espacio_fecha')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_prestamo_publico_horas')],
            },
        ),
    ]
