# Generated by Django 5.2.7 on 2026-03-24 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0005_tipoespacio_alter_espaciofisico_tipo'),
        ('prestamos', '0005_alter_prestamoespacio_options_prestamoespaciopublico'),
        ('usuarios', '0004_usuario_sede_usuario_idx_usuario_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoespacio',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='es_ocurrencia_generada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='es_recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='fin_repeticion_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='fin_repeticion_ocurrencias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='fin_repeticion_tipo',
            field=models.CharField(choices=[('never', 'Nunca'), ('until_date', 'Hasta una fecha'), ('count', 'Por numero de ocurrencias')], default='never', max_length=20),
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='frecuencia',
            field=models.CharField(choices=[('none', 'No se repite'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual'), ('weekdays', 'Dias laborales')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='intervalo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='prestamo_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocurrencias_generadas', to='prestamos.prestamoespacio'),
        ),
        migrations.AddField(
            model_name='prestamoespacio',
            name='serie_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='es_ocurrencia_generada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='es_recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='fin_repeticion_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='fin_repeticion_ocurrencias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='fin_repeticion_tipo',
            field=models.CharField(choices=[('never', 'Nunca'), ('until_date', 'Hasta una fecha'), ('count', 'Por numero de ocurrencias')], default='never', max_length=20),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='frecuencia',
            field=models.CharField(choices=[('none', 'No se repite'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual'), ('weekdays', 'Dias laborales')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='intervalo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='prestamo_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocurrencias_generadas_publicas', to='prestamos.prestamoespaciopublico'),
        ),
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='serie_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='prestamoespacio',
            index=models.Index(fields=['prestamo_padre', 'fecha'], name='idx_prestamo_padre_fecha'),
        ),
        migrations.AddIndex(
            model_name='prestamoespaciopublico',
            index=models.Index(fields=['prestamo_padre', 'fecha'], name='idx_pub_padre_fecha'),
        ),
    ]
