# Generated by Django 5.2.14 on 2026-05-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_prestamoespacio_dias_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoespaciopublico',
            name='token_publico',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
