# Generated by Django 4.2.26 on 2025-11-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.BigIntegerField()),
                ('rol_usuario', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('supervisor', 'Supervisor'), ('admin', 'Administrador')], default='estudiante', max_length=20)),
                ('tipo_notificacion', models.CharField(choices=[('cambio_aula', 'Cambio de Aula'), ('cancelacion_clase', 'Cancelación de Clase'), ('nueva_asignacion', 'Nueva Asignación'), ('aprobacion_prestamo', 'Aprobación de Préstamo'), ('rechazo_prestamo', 'Rechazo de Préstamo'), ('recordatorio_horario', 'Recordatorio de Horario'), ('alerta_recursos', 'Alerta de Recursos'), ('mensaje_sistema', 'Mensaje del Sistema')], max_length=50)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('id_relacion', models.BigIntegerField(blank=True, null=True)),
                ('tabla_relacion', models.CharField(blank=True, max_length=100, null=True)),
                ('es_leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['id_usuario', '-fecha_creacion'], name='notificacio_id_usua_ed5cb9_idx'), models.Index(fields=['es_leida'], name='notificacio_es_leid_658542_idx'), models.Index(fields=['tipo_notificacion'], name='notificacio_tipo_no_b31206_idx')],
            },
        ),
    ]
