# Generated by Django 4.2.26 on 2025-11-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='rol_usuario',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='titulo',
        ),
    ]
