# Generated by Django 5.2.7 on 2025-11-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_remove_notificacion_rol_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notificacion',
            name='notificacio_id_usua_ed5cb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificacion',
            name='notificacio_es_leid_658542_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificacion',
            name='notificacio_tipo_no_b31206_idx',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_lectura',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='id_relacion',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='tabla_relacion',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo_notificacion',
            field=models.CharField(max_length=100),
        ),
    ]
