# Generated by Django 4.2.26 on 2025-11-28 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaciofisico',
            name='recursos',
        ),
        migrations.CreateModel(
            name='EspacioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_permitidos', to='espacios.espaciofisico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_permitidos', to='usuarios.usuario')),
            ],
        ),
    ]
