# Generated by Django 4.2.26 on 2025-11-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_remove_espaciofisico_recursos_espaciopermitido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaciofisico',
            name='disponible',
        ),
        migrations.AddField(
            model_name='espaciofisico',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Mantenimiento', 'En Mantenimiento'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=20),
        ),
    ]
