# Generated by Django 4.2.26 on 2025-11-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_remove_espaciofisico_disponible_espaciofisico_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciofisico',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
            preserve_default=False,
        ),
    ]
