# Generated by Django 4.2.26 on 2025-11-29 22:51

from django.db import migrations, models
import django.db.models.deletion


def populate_tipo_espacios(apps, schema_editor):
    """Crear los tipos de espacio y migrar los datos existentes"""
    TipoEspacio = apps.get_model('espacios', 'TipoEspacio')
    EspacioFisico = apps.get_model('espacios', 'EspacioFisico')
    
    # Crear los tipos de espacio predefinidos
    tipos_predefinidos = [
        {"nombre": "Laboratorio", "descripcion": "Laboratorio equipado"},
        {"nombre": "Taller", "descripcion": "Espacio para trabajo práctico"},
        {"nombre": "Sala de Reuniones", "descripcion": "Sala pequeña para reuniones"},
        {'nombre': 'Sala recreacional', 'descripcion': 'Espacio para actividades recreativas'},
        {'nombre': 'Cancha', 'descripcion': 'Espacio deportivo'}
    ]
    
    # Crear los tipos
    tipos_creados = {}
    for tipo_data in tipos_predefinidos:
        tipo, created = TipoEspacio.objects.get_or_create(
            nombre=tipo_data['nombre'],
            defaults={'descripcion': tipo_data['descripcion']}
        )
        tipos_creados[tipo_data['nombre']] = tipo
    
    # Migrar los datos existentes de EspacioFisico
    for espacio in EspacioFisico.objects.all():
        if espacio.tipo_old:  # tipo_old es el campo temporal que mantendrá el valor string
            # Buscar el tipo correspondiente
            tipo_obj = tipos_creados.get(espacio.tipo_old)
            if tipo_obj:
                espacio.tipo_new = tipo_obj
                espacio.save()
            else:
                # Si el tipo no existe, crear uno nuevo o usar un tipo por defecto
                tipo_obj, created = TipoEspacio.objects.get_or_create(
                    nombre=espacio.tipo_old,
                    defaults={'descripcion': ''}
                )
                espacio.tipo_new = tipo_obj
                espacio.save()


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_espaciofisico_nombre'),
    ]

    operations = [
        # Paso 1: Crear el modelo TipoEspacio
        migrations.CreateModel(
            name='TipoEspacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        
        # Paso 2: Renombrar el campo tipo existente a tipo_old
        migrations.RenameField(
            model_name='espaciofisico',
            old_name='tipo',
            new_name='tipo_old',
        ),
        
        # Paso 3: Agregar el nuevo campo tipo_new como ForeignKey (nullable temporalmente)
        migrations.AddField(
            model_name='espaciofisico',
            name='tipo_new',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='espacios',
                to='espacios.tipoespacio'
            ),
        ),
        
        # Paso 4: Migrar los datos
        migrations.RunPython(populate_tipo_espacios, migrations.RunPython.noop),
        
        # Paso 5: Eliminar el campo antiguo tipo_old
        migrations.RemoveField(
            model_name='espaciofisico',
            name='tipo_old',
        ),
        
        # Paso 6: Renombrar tipo_new a tipo
        migrations.RenameField(
            model_name='espaciofisico',
            old_name='tipo_new',
            new_name='tipo',
        ),
        
        # Paso 7: Hacer el campo tipo no nullable
        migrations.AlterField(
            model_name='espaciofisico',
            name='tipo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='espacios',
                to='espacios.tipoespacio'
            ),
        ),
    ]
