# Generated by Django 4.2.26 on 2025-11-28 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facultades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='facultades.facultad'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['facultad'], name='idx_usuario_facultad'),
        ),
    ]
