# Generated by Django 5.2.7 on 2025-12-03 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultades', '0002_facultad_sede'),
        ('sedes', '0001_initial'),
        ('usuarios', '0002_usuario_facultad_usuario_idx_usuario_facultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='sedes.sede'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['sede'], name='idx_usuario_sede'),
        ),
    ]
