# Generated by Django 5.2.7 on 2026-05-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_stg_oracle_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgoracleestudiante',
            name='id_sede_oracle',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
