# Generated by Django 5.2.15 on 2026-08-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_rol_supervisa_espacios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='origen',
            field=models.CharField(choices=[('SIUL', 'SIUL'), ('SIHUL', 'SIHUL')], default='SIHUL', max_length=10),
        ),
    ]
