# Generated by Codex on 2026-08-13

from django.db import migrations, models
import django.db.models.deletion


def asignar_roles_a_barranquilla(apps, schema_editor):
    Rol = apps.get_model('usuarios', 'Rol')
    Seccional = apps.get_model('sedes', 'Seccional')

    seccional = (
        Seccional.objects.filter(ciudad__iexact='Barranquilla').first()
        or Seccional.objects.order_by('id').first()
    )
    if not seccional:
        return

    Rol.objects.filter(seccional__isnull=True).update(seccional_id=seccional.id)


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0004_oracle_staging_mapping_and_external_fields'),
        ('usuarios', '0012_usuario_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='rol',
            name='seccional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='sedes.seccional'),
        ),
        migrations.RunPython(asignar_roles_a_barranquilla, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['seccional'], name='idx_rol_seccional'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('seccional', 'nombre'), name='uniq_rol_seccional_nombre'),
        ),
    ]
