# Generated by Django 5.2.7 on 2026-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Recibida', 'Recibida'), ('Registrada', 'Registrada'), ('Radicada', 'Radicada'), ('Causada', 'Causada'), ('Alistada', 'Alistada'), ('Aprobada Auditoría', 'Aprobada Auditoría'), ('Rechazada Auditoría', 'Rechazada Auditoría'), ('Cargada', 'Cargada'), ('Revisada Dir. Financiera', 'Revisada Dir. Financiera'), ('Enviada Rectoría', 'Enviada Rectoría'), ('Autorizada', 'Autorizada'), ('Rechazada', 'Rechazada'), ('Pago Aplicado', 'Pago Aplicado'), ('Pagada', 'Pagada'), ('Devuelta', 'Devuelta'), ('Detenida', 'Detenida'), ('Anulada', 'Anulada')], default='Recibida', max_length=50),
        ),
    ]
