# Generated by Django 5.2.7 on 2026-05-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0005_factura_numero_confirmacion_rechazo_rectoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadjunto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos_financiero/%Y/%m/%d/'),
        ),
    ]
