# Generated by Django 5.2.7 on 2026-05-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0006_alter_documentoadjunto_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_inicio_etapa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
