# Generated by Django 5.2.7 on 2026-06-06 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0007_factura_fecha_inicio_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_bancario', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_banco_nombre'), models.Index(fields=['activo'], name='idx_banco_activo')],
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_cuenta', to='financiero.banco')),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Tipos de Cuenta',
                'ordering': ['banco__nombre', 'nombre'],
                'indexes': [models.Index(fields=['banco'], name='idx_tipo_cuenta_banco'), models.Index(fields=['activo'], name='idx_tipo_cuenta_activo')],
                'unique_together': {('banco', 'nombre')},
            },
        ),
    ]
