# Generated by Django 5.2.7 on 2026-06-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0014_documentoadjunto_nas_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfactura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
