# Generated by Django 4.2.26 on 2025-11-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='semestres',
            field=models.IntegerField(default=10),
        ),
    ]
