# Generated by Django 5.2.7 on 2025-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_programa_semestres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
