# Generated by Django 5.2.15 on 2026-08-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_stgoracleprograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='origen',
            field=models.CharField(choices=[('SIUL', 'SIUL'), ('SIHUL', 'SIHUL')], default='SIHUL', max_length=10),
        ),
    ]
